// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: teleport/mfa/v1/challenge.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2025 Gravitational, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// AuthenticateChallenge is a challenge for all MFA devices registered for a user.
///
/// Deprecated: Use teleport.mfa.v2.
///
/// NOTE: This message was marked as deprecated in the .proto file.
public nonisolated struct Teleport_Mfa_V1_AuthenticateChallenge: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Unique resource name for the issued challenge generated by the server. Should be treated as an opaque identifier
  /// and used as-is in subsequent API calls.
  public var name: String = String()

  /// Webauthn credential assertion used for login/authentication ceremonies. Holds a list of allowed credentials (one
  /// for each U2F or Webauthn device registered by the user).
  public var webauthnChallenge: Webauthn_CredentialAssertion {
    get {_webauthnChallenge ?? Webauthn_CredentialAssertion()}
    set {_webauthnChallenge = newValue}
  }
  /// Returns true if `webauthnChallenge` has been explicitly set.
  public var hasWebauthnChallenge: Bool {self._webauthnChallenge != nil}
  /// Clears the value of `webauthnChallenge`. Subsequent reads from it will return its default value.
  public mutating func clearWebauthnChallenge() {self._webauthnChallenge = nil}

  /// SSO MFA challenge. If set, the client can go to the IdP redirect URL to perform an MFA check and obtain an MFA
  /// token. This token paired with the request id can be used for verification.
  public var ssoChallenge: Teleport_Mfa_V1_SSOChallenge {
    get {_ssoChallenge ?? Teleport_Mfa_V1_SSOChallenge()}
    set {_ssoChallenge = newValue}
  }
  /// Returns true if `ssoChallenge` has been explicitly set.
  public var hasSsoChallenge: Bool {self._ssoChallenge != nil}
  /// Clears the value of `ssoChallenge`. Subsequent reads from it will return its default value.
  public mutating func clearSsoChallenge() {self._ssoChallenge = nil}

  /// Browser challenge allows a user to MFA in the browser, to get a WebAuthn
  /// response that is returned to the client to be used for verification.
  public var browserChallenge: Teleport_Mfa_V1_BrowserMFAChallenge {
    get {_browserChallenge ?? Teleport_Mfa_V1_BrowserMFAChallenge()}
    set {_browserChallenge = newValue}
  }
  /// Returns true if `browserChallenge` has been explicitly set.
  public var hasBrowserChallenge: Bool {self._browserChallenge != nil}
  /// Clears the value of `browserChallenge`. Subsequent reads from it will return its default value.
  public mutating func clearBrowserChallenge() {self._browserChallenge = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _webauthnChallenge: Webauthn_CredentialAssertion? = nil
  fileprivate var _ssoChallenge: Teleport_Mfa_V1_SSOChallenge? = nil
  fileprivate var _browserChallenge: Teleport_Mfa_V1_BrowserMFAChallenge? = nil
}

/// AuthenticateResponse is a response to AuthenticateChallenge using one of the MFA devices registered for a user.
///
/// Deprecated: Use teleport.mfa.v2.
///
/// NOTE: This message was marked as deprecated in the .proto file.
public nonisolated struct Teleport_Mfa_V1_AuthenticateResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Unique resource name for the issued challenge generated by the server. Should be treated as an opaque identifier
  /// and used as-is in subsequent API calls.
  public var name: String = String()

  /// Response to the challenge using one of the MFA devices.
  public var response: Teleport_Mfa_V1_AuthenticateResponse.OneOf_Response? = nil

  /// Response to a Webauthn challenge.
  public var webauthn: Webauthn_CredentialAssertionResponse {
    get {
      if case .webauthn(let v)? = response {return v}
      return Webauthn_CredentialAssertionResponse()
    }
    set {response = .webauthn(newValue)}
  }

  /// Response to an SSO challenge.
  public var sso: Teleport_Mfa_V1_SSOChallengeResponse {
    get {
      if case .sso(let v)? = response {return v}
      return Teleport_Mfa_V1_SSOChallengeResponse()
    }
    set {response = .sso(newValue)}
  }

  /// Response to a browser challenge.
  public var browser: Teleport_Mfa_V1_BrowserMFAResponse {
    get {
      if case .browser(let v)? = response {return v}
      return Teleport_Mfa_V1_BrowserMFAResponse()
    }
    set {response = .browser(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Response to the challenge using one of the MFA devices.
  public nonisolated enum OneOf_Response: Equatable, Sendable {
    /// Response to a Webauthn challenge.
    case webauthn(Webauthn_CredentialAssertionResponse)
    /// Response to an SSO challenge.
    case sso(Teleport_Mfa_V1_SSOChallengeResponse)
    /// Response to a browser challenge.
    case browser(Teleport_Mfa_V1_BrowserMFAResponse)

  }

  public init() {}
}

/// SSOChallenge contains SSO auth request details to perform an SSO MFA check.
///
/// Deprecated: Use teleport.mfa.v2.
///
/// NOTE: This message was marked as deprecated in the .proto file.
public nonisolated struct Teleport_Mfa_V1_SSOChallenge: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// ID of an SSO auth request.
  public var requestID: String = String()

  /// IdP redirect URL to initiate the SSO MFA flow.
  public var redirectURL: String = String()

  /// SSO device corresponding to the challenge.
  public var device: Types_SSOMFADevice {
    get {_device ?? Types_SSOMFADevice()}
    set {_device = newValue}
  }
  /// Returns true if `device` has been explicitly set.
  public var hasDevice: Bool {self._device != nil}
  /// Clears the value of `device`. Subsequent reads from it will return its default value.
  public mutating func clearDevice() {self._device = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _device: Types_SSOMFADevice? = nil
}

/// SSOChallengeResponse is a response to SSOChallenge.
///
/// Deprecated: Use teleport.mfa.v2.
///
/// NOTE: This message was marked as deprecated in the .proto file.
public nonisolated struct Teleport_Mfa_V1_SSOChallengeResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// ID of an SSO auth request.
  public var requestID: String = String()

  /// Secret token used to verify the user's SSO MFA session.
  public var token: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// BrowserMFAChallenge contains browser MFA request details to perform a browser MFA check.
///
/// Deprecated: Use teleport.mfa.v2.
///
/// NOTE: This message was marked as deprecated in the .proto file.
public nonisolated struct Teleport_Mfa_V1_BrowserMFAChallenge: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// RequestId is the ID of a browser MFA request.
  public var requestID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// BrowserMFAResponse is a response to BrowserMFAChallenge.
///
/// Deprecated: Use teleport.mfa.v2.
///
/// NOTE: This message was marked as deprecated in the .proto file.
public nonisolated struct Teleport_Mfa_V1_BrowserMFAResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// RequestId is the ID of a browser MFA request.
  public var requestID: String = String()

  /// WebauthnResponse is the WebAuthn credential assertion response from the browser MFA flow.
  public var webauthnResponse: Webauthn_CredentialAssertionResponse {
    get {_webauthnResponse ?? Webauthn_CredentialAssertionResponse()}
    set {_webauthnResponse = newValue}
  }
  /// Returns true if `webauthnResponse` has been explicitly set.
  public var hasWebauthnResponse: Bool {self._webauthnResponse != nil}
  /// Clears the value of `webauthnResponse`. Subsequent reads from it will return its default value.
  public mutating func clearWebauthnResponse() {self._webauthnResponse = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _webauthnResponse: Webauthn_CredentialAssertionResponse? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "teleport.mfa.v1"

nonisolated extension Teleport_Mfa_V1_AuthenticateChallenge: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AuthenticateChallenge"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}webauthn_challenge\0\u{3}sso_challenge\0\u{3}browser_challenge\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._webauthnChallenge) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._ssoChallenge) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._browserChallenge) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try { if let v = self._webauthnChallenge {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._ssoChallenge {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._browserChallenge {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Mfa_V1_AuthenticateChallenge, rhs: Teleport_Mfa_V1_AuthenticateChallenge) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs._webauthnChallenge != rhs._webauthnChallenge {return false}
    if lhs._ssoChallenge != rhs._ssoChallenge {return false}
    if lhs._browserChallenge != rhs._browserChallenge {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Mfa_V1_AuthenticateResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AuthenticateResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}webauthn\0\u{1}sso\0\u{1}browser\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try {
        var v: Webauthn_CredentialAssertionResponse?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .webauthn(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .webauthn(v)
        }
      }()
      case 3: try {
        var v: Teleport_Mfa_V1_SSOChallengeResponse?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .sso(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .sso(v)
        }
      }()
      case 4: try {
        var v: Teleport_Mfa_V1_BrowserMFAResponse?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .browser(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .browser(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    switch self.response {
    case .webauthn?: try {
      guard case .webauthn(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .sso?: try {
      guard case .sso(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .browser?: try {
      guard case .browser(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Mfa_V1_AuthenticateResponse, rhs: Teleport_Mfa_V1_AuthenticateResponse) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.response != rhs.response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Mfa_V1_SSOChallenge: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SSOChallenge"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{3}redirect_url\0\u{1}device\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.redirectURL) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._device) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    if !self.redirectURL.isEmpty {
      try visitor.visitSingularStringField(value: self.redirectURL, fieldNumber: 2)
    }
    try { if let v = self._device {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Mfa_V1_SSOChallenge, rhs: Teleport_Mfa_V1_SSOChallenge) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.redirectURL != rhs.redirectURL {return false}
    if lhs._device != rhs._device {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Mfa_V1_SSOChallengeResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SSOChallengeResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{1}token\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.token) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    if !self.token.isEmpty {
      try visitor.visitSingularStringField(value: self.token, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Mfa_V1_SSOChallengeResponse, rhs: Teleport_Mfa_V1_SSOChallengeResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.token != rhs.token {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Mfa_V1_BrowserMFAChallenge: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BrowserMFAChallenge"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Mfa_V1_BrowserMFAChallenge, rhs: Teleport_Mfa_V1_BrowserMFAChallenge) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Mfa_V1_BrowserMFAResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BrowserMFAResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{3}webauthn_response\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._webauthnResponse) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._webauthnResponse {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Mfa_V1_BrowserMFAResponse, rhs: Teleport_Mfa_V1_BrowserMFAResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._webauthnResponse != rhs._webauthnResponse {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
