// Generated from the Electron app's src/main/store.js DEFAULTS (node -e …).
// `defaultLocalPath` is "~" here and expanded at load.
enum StoreDefaults {
    static let json = #"""
{
 "version": 1,
 "profiles": [],
 "folders": [],
 "history": [],
 "workspace": null,
 "workspaces": {},
 "layouts": [],
 "defaultLayoutId": null,
 "snippets": [],
 "requestTemplates": [],
 "tshLogins": [],
 "downloads": [],
 "sessionNotes": [],
 "forwardFavorites": [],
 "netRequests": [],
 "netRuns": [],
 "execRuns": [],
 "macros": [],
 "hiddenMacros": [],
 "macroPins": [],
 "macroCategoryOrder": [],
 "s3Targets": [],
 "settings": {
  "theme": "dark",
  "accent": "blue",
  "skin": "none",
  "x11": "off",
  "mfaMode": "platform",
  "mfaHosts": [],
  "hostLogins": {},
  "hostUsers": {},
  "agentForward": false,
  "agentForwardHosts": {},
  "agentForwardClusters": {},
  "highlight": false,
  "highlightRules": [],
  "hiddenHighlightRules": [],
  "highlightHosts": {},
  "hiddenHosts": [],
  "showHiddenHosts": false,
  "starredHosts": [],
  "starredMode": "inline",
  "hostOrder": {},
  "sshConfigFiles": [],
  "transferLimitKb": 0,
  "windowBounds": {},
  "panelSizes": {},
  "showShellInTitle": false,
  "showPaneNetIcon": true,
  "hostColors": {},
  "carefulHosts": [],
  "terminalPalette": "app",
  "folderFavorites": [],
  "autoFlagLocal": [
   "~",
   "~/Desktop",
   "~/Documents",
   "~/Downloads"
  ],
  "autoFlagHost": [
   "~",
   "~/Desktop",
   "~/Documents",
   "~/Downloads",
   "/var/log",
   "/etc",
   "/tmp"
  ],
  "showHostTags": false,
  "showHeartbeats": false,
  "quietNodeFilter": "all",
  "hostGroupOrder": [],
  "hostFolders": [],
  "folderMembers": {},
  "sidebarHostLimit": 20,
  "hostsPaneView": "list",
  "hostsPaneFolders": true,
  "showFiledHosts": false,
  "hostIcons": {},
  "requestableGroups": {},
  "reasonRequired": {},
  "resourceRoles": {},
  "clusterIcons": {},
  "clusterColors": {},
  "watchedHosts": {},
  "showWatchMark": true,
  "requestMonitor": [],
  "requestMonitorMinutes": 5,
  "requestMonitorOpen": false,
  "requestMonitorAutoOpen": false,
  "requestMonitorPos": null,
  "requestMonitorStatus": {},
  "showTabActivity": true,
  "confirmLinkOpen": true,
  "confirmQuitWithSessions": true,
  "confirmCloseWithSessions": true,
  "tmuxDefault": false,
  "tmuxHosts": {},
  "tmuxClusters": {},
  "tmuxSessionName": "serverlife",
  "tmuxSessionNames": {},
  "connectAnim": "rotate",
  "recentLimit": 20,
  "quickConnects": [],
  "tourSeenVersion": 0,
  "tshHomes": [],
  "tshPath": "",
  "sshPath": "",
  "controlSocket": false,
  "autoRestoreWorkspace": false,
  "explorersVisible": true,
  "openFilesHosts": {},
  "openFilesClusters": {},
  "explorerPosition": "left",
  "fontSize": 13,
  "fontFamily": "SFMono-Regular, Menlo, monospace",
  "scrollback": 10000,
  "cursorBlink": true,
  "confirmOnClose": true,
  "followTerminalFolder": true,
  "refreshSeconds": 5,
  "nodeRefreshSeconds": 10,
  "staleNodeMinutes": 2,
  "showHiddenFiles": false,
  "foldersFirst": true,
  "show3dView": true,
  "showFileDetails": false,
  "beamProxies": [],
  "hiddenBeamProxies": [],
  "externalEditor": "",
  "openWithApps": [],
  "defaultLocalPath": "~",
  "bellSound": false
 }
}
"""#
}
