// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: teleport/lib/teleterm/vnet/v1/vnet_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Teleport
// Copyright (C) 2024 Gravitational, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// BackgroundItemStatus maps to SMAppServiceStatus of the Service Management framework in macOS.
/// https://developer.apple.com/documentation/servicemanagement/smappservice/status-swift.enum?language=objc
public nonisolated enum Teleport_Lib_Teleterm_Vnet_V1_BackgroundItemStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case notRegistered // = 1

  /// This is the status the background item should have before tsh attempts to send a message to the
  /// daemon.
  case enabled // = 2
  case requiresApproval // = 3
  case notFound // = 4
  case notSupported // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .notRegistered
    case 2: self = .enabled
    case 3: self = .requiresApproval
    case 4: self = .notFound
    case 5: self = .notSupported
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .notRegistered: return 1
    case .enabled: return 2
    case .requiresApproval: return 3
    case .notFound: return 4
    case .notSupported: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Teleport_Lib_Teleterm_Vnet_V1_BackgroundItemStatus] = [
    .unspecified,
    .notRegistered,
    .enabled,
    .requiresApproval,
    .notFound,
    .notSupported,
  ]

}

/// WindowsServiceStatus maps to service-related errors in golang.org/x/sys/windows/zerrors_windows.go.
public nonisolated enum Teleport_Lib_Teleterm_Vnet_V1_WindowsServiceStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case ok // = 1
  case doesNotExist // = 2

  /// The VNet service cannot start because its version differs from the client.
  case versionMismatch // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .ok
    case 2: self = .doesNotExist
    case 3: self = .versionMismatch
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .ok: return 1
    case .doesNotExist: return 2
    case .versionMismatch: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Teleport_Lib_Teleterm_Vnet_V1_WindowsServiceStatus] = [
    .unspecified,
    .ok,
    .doesNotExist,
    .versionMismatch,
  ]

}

/// Request for Start.
public nonisolated struct Teleport_Lib_Teleterm_Vnet_V1_StartRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Response for Start.
public nonisolated struct Teleport_Lib_Teleterm_Vnet_V1_StartResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Request for Stop.
public nonisolated struct Teleport_Lib_Teleterm_Vnet_V1_StopRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Response for Stop.
public nonisolated struct Teleport_Lib_Teleterm_Vnet_V1_StopResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Request for GetServiceInfo.
public nonisolated struct Teleport_Lib_Teleterm_Vnet_V1_GetServiceInfoRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// GetServiceInfoResponse contains the status of the running VNet service.
public nonisolated struct Teleport_Lib_Teleterm_Vnet_V1_GetServiceInfoResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// app_dns_zones is a deduplicated list of all DNS zones valid as DNS
  /// suffixes for connections to TCP apps.
  public var appDnsZones: [String] = []

  /// clusters is a list of cluster names valid as DNS suffixes for SSH hosts.
  public var clusters: [String] = []

  /// ssh_configured is true if the user's SSH config file includes VNet's
  /// generated SSH config necessary for SSH access.
  public var sshConfigured: Bool = false

  /// vnet_ssh_config_path is the path of VNet's generated OpenSSH-compatible
  /// config file.
  public var vnetSshConfigPath: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Request for GetBackgroundItemStatus.
public nonisolated struct Teleport_Lib_Teleterm_Vnet_V1_GetBackgroundItemStatusRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Response for GetBackgroundItemStatus.
public nonisolated struct Teleport_Lib_Teleterm_Vnet_V1_GetBackgroundItemStatusResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var status: Teleport_Lib_Teleterm_Vnet_V1_BackgroundItemStatus = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Request for CheckInstallTimeRequirementsRequest.
public nonisolated struct Teleport_Lib_Teleterm_Vnet_V1_CheckInstallTimeRequirementsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Response for CheckInstallTimeRequirementsResponse.
public nonisolated struct Teleport_Lib_Teleterm_Vnet_V1_CheckInstallTimeRequirementsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var status: Teleport_Lib_Teleterm_Vnet_V1_CheckInstallTimeRequirementsResponse.OneOf_Status? = nil

  public var windowsServiceStatus: Teleport_Lib_Teleterm_Vnet_V1_WindowsServiceStatus {
    get {
      if case .windowsServiceStatus(let v)? = status {return v}
      return .unspecified
    }
    set {status = .windowsServiceStatus(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Status: Equatable, Sendable {
    case windowsServiceStatus(Teleport_Lib_Teleterm_Vnet_V1_WindowsServiceStatus)

  }

  public init() {}
}

/// Request for RunDiagnostics.
public nonisolated struct Teleport_Lib_Teleterm_Vnet_V1_RunDiagnosticsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Response for RunDiagnostics.
public nonisolated struct Teleport_Lib_Teleterm_Vnet_V1_RunDiagnosticsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var report: Teleport_Lib_Vnet_Diag_V1_Report {
    get {_report ?? Teleport_Lib_Vnet_Diag_V1_Report()}
    set {_report = newValue}
  }
  /// Returns true if `report` has been explicitly set.
  public var hasReport: Bool {self._report != nil}
  /// Clears the value of `report`. Subsequent reads from it will return its default value.
  public mutating func clearReport() {self._report = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _report: Teleport_Lib_Vnet_Diag_V1_Report? = nil
}

/// Request for AutoConfigureSSH.
public nonisolated struct Teleport_Lib_Teleterm_Vnet_V1_AutoConfigureSSHRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Response for AutoConfigureSSH.
public nonisolated struct Teleport_Lib_Teleterm_Vnet_V1_AutoConfigureSSHResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "teleport.lib.teleterm.vnet.v1"

nonisolated extension Teleport_Lib_Teleterm_Vnet_V1_BackgroundItemStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0BACKGROUND_ITEM_STATUS_UNSPECIFIED\0\u{1}BACKGROUND_ITEM_STATUS_NOT_REGISTERED\0\u{1}BACKGROUND_ITEM_STATUS_ENABLED\0\u{1}BACKGROUND_ITEM_STATUS_REQUIRES_APPROVAL\0\u{1}BACKGROUND_ITEM_STATUS_NOT_FOUND\0\u{1}BACKGROUND_ITEM_STATUS_NOT_SUPPORTED\0")
}

nonisolated extension Teleport_Lib_Teleterm_Vnet_V1_WindowsServiceStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0WINDOWS_SERVICE_STATUS_UNSPECIFIED\0\u{1}WINDOWS_SERVICE_STATUS_OK\0\u{1}WINDOWS_SERVICE_STATUS_DOES_NOT_EXIST\0\u{1}WINDOWS_SERVICE_STATUS_VERSION_MISMATCH\0")
}

nonisolated extension Teleport_Lib_Teleterm_Vnet_V1_StartRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StartRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_Vnet_V1_StartRequest, rhs: Teleport_Lib_Teleterm_Vnet_V1_StartRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_Vnet_V1_StartResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StartResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_Vnet_V1_StartResponse, rhs: Teleport_Lib_Teleterm_Vnet_V1_StartResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_Vnet_V1_StopRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StopRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_Vnet_V1_StopRequest, rhs: Teleport_Lib_Teleterm_Vnet_V1_StopRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_Vnet_V1_StopResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StopResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_Vnet_V1_StopResponse, rhs: Teleport_Lib_Teleterm_Vnet_V1_StopResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_Vnet_V1_GetServiceInfoRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetServiceInfoRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_Vnet_V1_GetServiceInfoRequest, rhs: Teleport_Lib_Teleterm_Vnet_V1_GetServiceInfoRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_Vnet_V1_GetServiceInfoResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetServiceInfoResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}app_dns_zones\0\u{1}clusters\0\u{3}ssh_configured\0\u{3}vnet_ssh_config_path\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.appDnsZones) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.clusters) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.sshConfigured) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.vnetSshConfigPath) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.appDnsZones.isEmpty {
      try visitor.visitRepeatedStringField(value: self.appDnsZones, fieldNumber: 1)
    }
    if !self.clusters.isEmpty {
      try visitor.visitRepeatedStringField(value: self.clusters, fieldNumber: 2)
    }
    if self.sshConfigured != false {
      try visitor.visitSingularBoolField(value: self.sshConfigured, fieldNumber: 3)
    }
    if !self.vnetSshConfigPath.isEmpty {
      try visitor.visitSingularStringField(value: self.vnetSshConfigPath, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_Vnet_V1_GetServiceInfoResponse, rhs: Teleport_Lib_Teleterm_Vnet_V1_GetServiceInfoResponse) -> Bool {
    if lhs.appDnsZones != rhs.appDnsZones {return false}
    if lhs.clusters != rhs.clusters {return false}
    if lhs.sshConfigured != rhs.sshConfigured {return false}
    if lhs.vnetSshConfigPath != rhs.vnetSshConfigPath {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_Vnet_V1_GetBackgroundItemStatusRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetBackgroundItemStatusRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_Vnet_V1_GetBackgroundItemStatusRequest, rhs: Teleport_Lib_Teleterm_Vnet_V1_GetBackgroundItemStatusRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_Vnet_V1_GetBackgroundItemStatusResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetBackgroundItemStatusResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}status\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.status != .unspecified {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_Vnet_V1_GetBackgroundItemStatusResponse, rhs: Teleport_Lib_Teleterm_Vnet_V1_GetBackgroundItemStatusResponse) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_Vnet_V1_CheckInstallTimeRequirementsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CheckInstallTimeRequirementsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_Vnet_V1_CheckInstallTimeRequirementsRequest, rhs: Teleport_Lib_Teleterm_Vnet_V1_CheckInstallTimeRequirementsRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_Vnet_V1_CheckInstallTimeRequirementsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CheckInstallTimeRequirementsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}windows_service_status\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Teleport_Lib_Teleterm_Vnet_V1_WindowsServiceStatus?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.status != nil {try decoder.handleConflictingOneOf()}
          self.status = .windowsServiceStatus(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if case .windowsServiceStatus(let v)? = self.status {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_Vnet_V1_CheckInstallTimeRequirementsResponse, rhs: Teleport_Lib_Teleterm_Vnet_V1_CheckInstallTimeRequirementsResponse) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_Vnet_V1_RunDiagnosticsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RunDiagnosticsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_Vnet_V1_RunDiagnosticsRequest, rhs: Teleport_Lib_Teleterm_Vnet_V1_RunDiagnosticsRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_Vnet_V1_RunDiagnosticsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RunDiagnosticsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}report\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._report) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._report {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_Vnet_V1_RunDiagnosticsResponse, rhs: Teleport_Lib_Teleterm_Vnet_V1_RunDiagnosticsResponse) -> Bool {
    if lhs._report != rhs._report {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_Vnet_V1_AutoConfigureSSHRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AutoConfigureSSHRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_Vnet_V1_AutoConfigureSSHRequest, rhs: Teleport_Lib_Teleterm_Vnet_V1_AutoConfigureSSHRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_Vnet_V1_AutoConfigureSSHResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AutoConfigureSSHResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_Vnet_V1_AutoConfigureSSHResponse, rhs: Teleport_Lib_Teleterm_Vnet_V1_AutoConfigureSSHResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
