import Foundation

/// Export a multi-exec selection as a runnable Ansible bundle (ansible.js).
///
/// The ad-hoc command you just ran across N hosts and an Ansible playbook
/// describe the same intent; this turns the former into the latter so throwaway
/// work can become something reviewable and repeatable.
///
/// Teleport hosts reach their nodes through a generated tsh ssh_config, copied
/// into the bundle so it runs standalone.
enum AnsibleExport {
    struct Target: Equatable {
        var type: String          // "teleport" | "ssh"
        var name: String?
        var alias: String?
        var hostname: String?
        var cluster: String?
        var proxy: String?
        var home: String?
        var login: String?
        var user: String?
        var port: Int?
    }

    struct Group {
        var key: String
        var type: String
        var cluster: String?
        var proxy: String?
        var hosts: [Target]
    }

    struct Bundle {
        var inventory: String
        var playbook: String
        var cfg: String
        var run: String
        var readme: String
        var groups: [Group]
    }

    struct Options {
        var playName: String?
        var become = false
        var forks: Int?
    }

    /// Quote a scalar for YAML only when it needs it.
    static func y(_ value: String?) -> String {
        let s = value ?? ""
        if s.isEmpty { return "''" }
        if s.range(of: "^[A-Za-z0-9_./@-]+$", options: .regularExpression) != nil { return s }
        return "'" + s.replacingOccurrences(of: "'", with: "''") + "'"
    }

    static func slug(_ s: String?) -> String {
        var t = (s ?? "").replacingOccurrences(of: "[^A-Za-z0-9_]+", with: "_", options: .regularExpression)
        t = t.replacingOccurrences(of: "^_+|_+$", with: "", options: .regularExpression)
        return t.isEmpty ? "group" : t
    }

    static func sshConfigName(_ g: Group) -> String {
        "tsh-\(slug(g.cluster?.nilIfEmpty ?? g.proxy)).conf"
    }

    static func build(_ targets: [Target], command: String, _ opts: Options = Options(), now: Date = Date()) -> Bundle {
        let playName = opts.playName?.nilIfEmpty ?? "ServerLife multi-exec export"
        let become = opts.become
        let forks = opts.forks ?? min(20, max(5, targets.count))

        // Group by cluster so each Teleport cluster gets its own ssh_config var.
        var groups: [Group] = []
        for t in targets {
            let key = t.type == "teleport" ? "teleport_" + slug(t.cluster) : "ssh_hosts"
            if let i = groups.firstIndex(where: { $0.key == key }) { groups[i].hosts.append(t) }
            else { groups.append(Group(key: key, type: t.type, cluster: t.cluster, proxy: t.proxy, hosts: [t])) }
        }

        /* ---------- inventory.yml ---------- */
        var lines = ["---", "# Generated by ServerLife", "all:", "  children:"]
        for g in groups {
            lines.append("    \(g.key):")
            lines.append("      hosts:")
            for t in g.hosts {
                let invName = slug(t.name?.nilIfEmpty ?? t.alias)
                lines.append("        \(invName):")
                if t.type == "teleport" {
                    // The tsh config maps <node>.<cluster> to a ProxyCommand.
                    lines.append("          ansible_host: \(y("\(t.name ?? "undefined").\(t.cluster ?? "undefined")"))")
                } else {
                    lines.append("          ansible_host: \(y(t.alias))")
                }
                if let l = t.login?.nilIfEmpty { lines.append("          ansible_user: \(y(l))") }
                else if let u = t.user?.nilIfEmpty { lines.append("          ansible_user: \(y(u))") }
                if t.type != "teleport", let p = t.port, p != 0, p != 22 {
                    lines.append("          ansible_port: \(p)")
                }
            }
            lines.append("      vars:")
            if g.type == "teleport" {
                lines.append("        ansible_port: 3022")
                lines.append("        ansible_ssh_common_args: \(y("-F ./ssh_config/" + sshConfigName(g)))")
            } else {
                // Plain hosts already resolve through the user's own ~/.ssh/config.
                lines.append("        ansible_ssh_common_args: \(y("-o StrictHostKeyChecking=accept-new"))")
            }
            lines.append("")
        }
        let inventory = lines.joined(separator: "\n") + "\n"

        /* ---------- playbook.yml ---------- */
        let indented = command.components(separatedBy: "\n").map { "          " + $0 }.joined(separator: "\n")
        var pb: [String?] = [
            "---",
            "# Generated by ServerLife from a multi-exec command.",
            "- name: \(y(playName))",
            "  hosts: all",
            "  gather_facts: false",
            become ? "  become: true" : nil,
            "  strategy: free",
            "  tasks:",
        ]
        /*
         * `raw`, not `shell`: the command goes over SSH as it is, the way
         * multi-exec ran it, with nothing needed on the host. `shell` ships a
         * Python module across, and current Ansible's modules no longer run on
         * the Python of an older image — Amazon Linux 2's 3.7 fails to parse them
         * — so a `df` that worked in multi-exec came back from the export as
         * "rc=1, command failed" without having run.
         */
        pb += [
            "    - name: Run command",
            "      ansible.builtin.raw: |",
            indented,
            "      register: result",
            "      changed_when: false",
            "      failed_when: false",
            "",
            "    - name: Report",
            "      ansible.builtin.debug:",
            "        msg: \"rc={{ result.rc }} {{ result.stdout_lines | default([]) }}\"",
            "",
            // What went wrong in its own words: the command's stderr, else Ansible's
            // message (a connection or module failure has no stderr), else the code.
            "    - name: Fail the host if the command failed",
            "      ansible.builtin.fail:",
            "        msg: \"{{ (result.stderr | default('') | trim) or (result.msg | default('')) or ('exited ' ~ result.rc) }}\"",
            "      when: result.rc != 0",
            "",
        ]
        let playbook = pb.compactMap { $0 }.joined(separator: "\n")

        /* ---------- ansible.cfg ---------- */
        let cfg = [
            "# Generated by ServerLife",
            "[defaults]",
            "inventory = ./inventory.yml",
            "host_key_checking = False",
            /*
             * YAML output from Ansible's own callback. `stdout_callback = yaml` named
             * community.general's plugin, which that collection removed in 12.0 —
             * a current install refuses to run at all with it set. ansible-core 2.13
             * and later do the same with the built-in callback; older ones ignore
             * the key and print their usual output.
             */
            "stdout_callback = ansible.builtin.default",
            "callback_result_format = yaml",
            "forks = \(forks)",
            "interpreter_python = auto_silent",
            "",
            "[ssh_connection]",
            "pipelining = True",
            // No terminal for `raw`: with one, every host prints its login banner
            // (motd, "updates available") ahead of the command's output.
            "usetty = False",
            "",
        ].joined(separator: "\n")

        /* ---------- run.sh ---------- */
        let run = [
            "#!/usr/bin/env bash",
            "# Generated by ServerLife.",
            "set -euo pipefail",
            "cd \"$(dirname \"$0\")\"",
            "",
            "# Teleport hosts need a valid tsh certificate; log in first if needed:",
            "#   tsh login --proxy=<proxy>",
            "",
            "exec ansible-playbook playbook.yml \"$@\"",
            "",
        ].joined(separator: "\n")

        let readme = [
            "# ServerLife → Ansible export",
            "",
            "Generated \(MultiExecFile.iso(now))",
            "",
            "Hosts: \(targets.count)",
            "",
            "## Run",
            "",
            "```sh",
            "./run.sh",
            "# or:",
            "ansible-playbook playbook.yml",
            "```",
            "",
            "## Notes",
            "",
            "- Teleport hosts connect through `ssh_config/`, generated by `tsh config`.",
            "  Those files reference your local `~/.tsh` certificates, so run `tsh login`",
            "  before the playbook if your session has expired.",
            "- Plain SSH hosts resolve through your own `~/.ssh/config`.",
            "- The command runs via `ansible.builtin.raw`: straight over SSH, as",
            "  multi-exec ran it, so it needs nothing on the host — not even Python.",
            "- If it is really a package, service or file change, swap in the matching",
            "  module — that is the point of moving it here. Modules do need Python on",
            "  the host, and current Ansible needs a current one: Amazon Linux 2's",
            "  Python 3.7, for one, is too old. Check `python3 --version` there first.",
            "",
        ].joined(separator: "\n")

        return Bundle(inventory: inventory, playbook: playbook, cfg: cfg, run: run, readme: readme, groups: groups)
    }

    struct Written {
        var dir: String
        var files: [String]
    }

    /// Write the bundle to disk, including a copy of each tsh ssh_config.
    /// `teleport: false` skips the ssh_config generation (tests).
    static func write(_ dir: String, _ bundle: Bundle, teleport: Bool = true) async throws -> Written {
        let fm = FileManager.default
        try fm.createDirectory(atPath: dir, withIntermediateDirectories: true)
        func put(_ name: String, _ text: String, mode: Int? = nil) throws {
            let p = (dir as NSString).appendingPathComponent(name)
            try Data(text.utf8).write(to: URL(fileURLWithPath: p))
            if let mode { try fm.setAttributes([.posixPermissions: mode], ofItemAtPath: p) }
        }
        try put("inventory.yml", bundle.inventory)
        try put("playbook.yml", bundle.playbook)
        try put("ansible.cfg", bundle.cfg)
        try put("README.md", bundle.readme)
        try put("run.sh", bundle.run, mode: 0o755)
        var written = ["inventory.yml", "playbook.yml", "ansible.cfg", "README.md", "run.sh"]

        let tp = bundle.groups.filter { $0.type == "teleport" }
        if !tp.isEmpty && teleport {
            let cfgDir = (dir as NSString).appendingPathComponent("ssh_config")
            try fm.createDirectory(atPath: cfgDir, withIntermediateDirectories: true)
            for g in tp {
                let want = (cfgDir as NSString).appendingPathComponent(sshConfigName(g))
                do {
                    let generated = try await TeleportSSH.writeClusterSshConfig(dir: cfgDir, proxy: g.proxy, cluster: g.cluster, home: nil)
                    if generated != want {
                        try? fm.removeItem(atPath: want)
                        try fm.moveItem(atPath: generated, toPath: want)
                    }
                    written.append("ssh_config/" + sshConfigName(g))
                } catch {
                    let msg = (error as? AppError)?.message ?? error.localizedDescription
                    try Data("# Could not generate automatically: \(msg)\n# Run: tsh --proxy=\(g.proxy ?? "undefined") config > \(sshConfigName(g))\n".utf8)
                        .write(to: URL(fileURLWithPath: want))
                    written.append("ssh_config/" + sshConfigName(g) + " (placeholder)")
                }
            }
        }
        return Written(dir: dir, files: written)
    }

    /**
     * A folder name for an export, safe on every platform.
     *
     * It is typed by a person, so it may hold anything: a slash would put the
     * bundle somewhere else entirely, and Windows refuses a further handful of
     * characters and names that end in a dot or a space. Those are dropped or
     * replaced rather than refused, since what was meant is obvious; a name with
     * nothing left falls back to the old default.
     */
    static func exportFolderName(_ name: String?) -> String {
        var s = name ?? ""
        s = s.replacingOccurrences(of: "[\\x{0000}-\\x{001f}<>:\"/\\\\|?*]+", with: "-", options: .regularExpression)
        s = s.replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
        s = s.replacingOccurrences(of: "^[\\s.-]+|[\\s.-]+$", with: "", options: .regularExpression)
        // .slice(0, 80) counts UTF-16 units.
        let u = Array(s.utf16)
        if u.count > 80 { s = String(decoding: u[0..<80], as: UTF16.self) }
        s = s.trimmingCharacters(in: .whitespacesAndNewlines)
        if s.isEmpty || s.range(of: "^(con|prn|aux|nul|com\\d|lpt\\d)$", options: [.regularExpression, .caseInsensitive]) != nil {
            return "serverlife-ansible"
        }
        return s
    }

    /// A name to suggest: the command's first word, as `ansible-<word>`.
    static func suggestFolderName(_ command: String?) -> String {
        let word = (command ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
            .split(whereSeparator: { $0.isWhitespace }).first.map(String.init) ?? ""
        // Not slug(): that falls back to "group" for an inventory, which is no name
        // for a folder.
        var s = word.components(separatedBy: "/").last ?? ""
        s = s.replacingOccurrences(of: "[^A-Za-z0-9_-]+", with: "-", options: .regularExpression)
        s = s.replacingOccurrences(of: "^-+|-+$", with: "", options: .regularExpression)
        return s.isEmpty ? "serverlife-ansible" : "ansible-\(s)"
    }
}
