// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: teleport/legacy/types/mfa_device.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2025 Gravitational, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// MFADevice is a multi-factor authentication device, such as a security key or
/// an OTP app.
public nonisolated struct Types_MFADevice: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Boilerplate for implementing the Resource interface.
  public var kind: String {
    get {_storage._kind}
    set {_uniqueStorage()._kind = newValue}
  }

  public var subKind: String {
    get {_storage._subKind}
    set {_uniqueStorage()._subKind = newValue}
  }

  public var version: String {
    get {_storage._version}
    set {_uniqueStorage()._version = newValue}
  }

  public var metadata: Types_Metadata {
    get {_storage._metadata ?? Types_Metadata()}
    set {_uniqueStorage()._metadata = newValue}
  }
  /// Returns true if `metadata` has been explicitly set.
  public var hasMetadata: Bool {_storage._metadata != nil}
  /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
  public mutating func clearMetadata() {_uniqueStorage()._metadata = nil}

  /// ID is a UUID of this device.
  public var id: String {
    get {_storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  public var addedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_storage._addedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._addedAt = newValue}
  }
  /// Returns true if `addedAt` has been explicitly set.
  public var hasAddedAt: Bool {_storage._addedAt != nil}
  /// Clears the value of `addedAt`. Subsequent reads from it will return its default value.
  public mutating func clearAddedAt() {_uniqueStorage()._addedAt = nil}

  public var lastUsed: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_storage._lastUsed ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._lastUsed = newValue}
  }
  /// Returns true if `lastUsed` has been explicitly set.
  public var hasLastUsed: Bool {_storage._lastUsed != nil}
  /// Clears the value of `lastUsed`. Subsequent reads from it will return its default value.
  public mutating func clearLastUsed() {_uniqueStorage()._lastUsed = nil}

  public var device: OneOf_Device? {
    get {return _storage._device}
    set {_uniqueStorage()._device = newValue}
  }

  public var totp: Types_TOTPDevice {
    get {
      if case .totp(let v)? = _storage._device {return v}
      return Types_TOTPDevice()
    }
    set {_uniqueStorage()._device = .totp(newValue)}
  }

  public var u2F: Types_U2FDevice {
    get {
      if case .u2F(let v)? = _storage._device {return v}
      return Types_U2FDevice()
    }
    set {_uniqueStorage()._device = .u2F(newValue)}
  }

  public var webauthn: Types_WebauthnDevice {
    get {
      if case .webauthn(let v)? = _storage._device {return v}
      return Types_WebauthnDevice()
    }
    set {_uniqueStorage()._device = .webauthn(newValue)}
  }

  public var sso: Types_SSOMFADevice {
    get {
      if case .sso(let v)? = _storage._device {return v}
      return Types_SSOMFADevice()
    }
    set {_uniqueStorage()._device = .sso(newValue)}
  }

  public var browser: Types_BrowserMFADevice {
    get {
      if case .browser(let v)? = _storage._device {return v}
      return Types_BrowserMFADevice()
    }
    set {_uniqueStorage()._device = .browser(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Device: Equatable, Sendable {
    case totp(Types_TOTPDevice)
    case u2F(Types_U2FDevice)
    case webauthn(Types_WebauthnDevice)
    case sso(Types_SSOMFADevice)
    case browser(Types_BrowserMFADevice)

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// TOTPDevice holds the TOTP-specific fields of MFADevice.
public nonisolated struct Types_TOTPDevice: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var key: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// U2FDevice holds the U2F-specific fields of MFADevice.
public nonisolated struct Types_U2FDevice: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// KeyHandle uniquely identifies a key on a device
  public var keyHandle: Data = Data()

  /// PubKey is an DER encoded ecdsa public key
  public var pubKey: Data = Data()

  /// Counter is the latest seen value of the U2F usage counter.
  public var counter: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// WebauthnDevice holds Webauthn-specific fields of MFADevice.
public nonisolated struct Types_WebauthnDevice: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Credential ID for the authenticator.
  public var credentialID: Data = Data()

  /// Public key encoded in CBOR format.
  /// Webauthn support various key algorithms; CBOR encoding is used to reflect
  /// those choices.
  /// See https://w3c.github.io/webauthn/#sctn-alg-identifier for a starter
  /// reference.
  public var publicKeyCbor: Data = Data()

  /// Attestation format used by the authenticator, if any.
  public var attestationType: String = String()

  /// AAGUID is the globally unique identifier of the authenticator model.
  /// Zeroed for U2F devices.
  public var aaguid: Data = Data()

  /// Signature counter for login operations.
  /// Actual counter values received from the authenticator are expected to be
  /// higher than the previously-stored value.
  public var signatureCounter: UInt32 = 0

  /// Raw attestation object, as returned by the authentication during
  /// registration.
  /// Absent for legacy entries (Teleport 8.x).
  public var attestationObject: Data = Data()

  /// True if a resident key was requested during registration.
  /// Marks passwordless-capable devices.
  /// (Note that resident_key=true represents the server-side / Relying Party
  /// view of the registration process; the authenticator alone can determine
  /// if a key is truly resident.)
  public var residentKey: Bool = false

  /// Relying Party ID used by the credential.
  /// Recorded on registration for new credentials, or on first successful
  /// authentication for "old" credentials (created before the field existed).
  /// Ideally, this is always the same as the configured RPID.
  /// If an RPID change does happen, this helps Teleport detect it and react
  /// accordingly.
  public var credentialRpID: String = String()

  /// Authenticator Backup Eligibility (BE) bit, recorded during registration or
  /// backfill (for older authenticators).
  /// https://w3c.github.io/webauthn/#authdata-flags-be
  public var credentialBackupEligible: SwiftProtobuf.Google_Protobuf_BoolValue {
    get {_credentialBackupEligible ?? SwiftProtobuf.Google_Protobuf_BoolValue()}
    set {_credentialBackupEligible = newValue}
  }
  /// Returns true if `credentialBackupEligible` has been explicitly set.
  public var hasCredentialBackupEligible: Bool {self._credentialBackupEligible != nil}
  /// Clears the value of `credentialBackupEligible`. Subsequent reads from it will return its default value.
  public mutating func clearCredentialBackupEligible() {self._credentialBackupEligible = nil}

  /// Authenticator Backup State (BS) bit, recorded during registration or
  /// backfill (for older authenticators).
  /// https://w3c.github.io/webauthn/#authdata-flags-bs
  public var credentialBackedUp: SwiftProtobuf.Google_Protobuf_BoolValue {
    get {_credentialBackedUp ?? SwiftProtobuf.Google_Protobuf_BoolValue()}
    set {_credentialBackedUp = newValue}
  }
  /// Returns true if `credentialBackedUp` has been explicitly set.
  public var hasCredentialBackedUp: Bool {self._credentialBackedUp != nil}
  /// Clears the value of `credentialBackedUp`. Subsequent reads from it will return its default value.
  public mutating func clearCredentialBackedUp() {self._credentialBackedUp = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _credentialBackupEligible: SwiftProtobuf.Google_Protobuf_BoolValue? = nil
  fileprivate var _credentialBackedUp: SwiftProtobuf.Google_Protobuf_BoolValue? = nil
}

/// SSOMFADevice contains details of an SSO MFA method.
public nonisolated struct Types_SSOMFADevice: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// connector_id is the ID of the SSO connector.
  public var connectorID: String = String()

  /// connector_type is the type of the SSO connector.
  public var connectorType: String = String()

  /// display_name is the display name of the SSO connector
  public var displayName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// BrowserMFADevice is a synthetic MFA device that is made available if a user
/// has at least one WebAuthn device and no SSO MFA setup. This message doesn't
/// require any fields, it just needs to exist so it can be an MFA option.
public nonisolated struct Types_BrowserMFADevice: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "types"

nonisolated extension Types_MFADevice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MFADevice"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}kind\0\u{3}sub_kind\0\u{1}version\0\u{1}metadata\0\u{1}id\0\u{3}added_at\0\u{3}last_used\0\u{1}totp\0\u{1}u2f\0\u{1}webauthn\0\u{1}sso\0\u{1}browser\0")

  fileprivate class _StorageClass {
    var _kind: String = String()
    var _subKind: String = String()
    var _version: String = String()
    var _metadata: Types_Metadata? = nil
    var _id: String = String()
    var _addedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _lastUsed: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _device: Types_MFADevice.OneOf_Device?

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _kind = source._kind
      _subKind = source._subKind
      _version = source._version
      _metadata = source._metadata
      _id = source._id
      _addedAt = source._addedAt
      _lastUsed = source._lastUsed
      _device = source._device
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._kind) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._subKind) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._version) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._metadata) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._id) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._addedAt) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._lastUsed) }()
        case 8: try {
          var v: Types_TOTPDevice?
          var hadOneofValue = false
          if let current = _storage._device {
            hadOneofValue = true
            if case .totp(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._device = .totp(v)
          }
        }()
        case 9: try {
          var v: Types_U2FDevice?
          var hadOneofValue = false
          if let current = _storage._device {
            hadOneofValue = true
            if case .u2F(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._device = .u2F(v)
          }
        }()
        case 10: try {
          var v: Types_WebauthnDevice?
          var hadOneofValue = false
          if let current = _storage._device {
            hadOneofValue = true
            if case .webauthn(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._device = .webauthn(v)
          }
        }()
        case 11: try {
          var v: Types_SSOMFADevice?
          var hadOneofValue = false
          if let current = _storage._device {
            hadOneofValue = true
            if case .sso(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._device = .sso(v)
          }
        }()
        case 12: try {
          var v: Types_BrowserMFADevice?
          var hadOneofValue = false
          if let current = _storage._device {
            hadOneofValue = true
            if case .browser(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._device = .browser(v)
          }
        }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._kind.isEmpty {
        try visitor.visitSingularStringField(value: _storage._kind, fieldNumber: 1)
      }
      if !_storage._subKind.isEmpty {
        try visitor.visitSingularStringField(value: _storage._subKind, fieldNumber: 2)
      }
      if !_storage._version.isEmpty {
        try visitor.visitSingularStringField(value: _storage._version, fieldNumber: 3)
      }
      try { if let v = _storage._metadata {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      if !_storage._id.isEmpty {
        try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 5)
      }
      try { if let v = _storage._addedAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._lastUsed {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      switch _storage._device {
      case .totp?: try {
        guard case .totp(let v)? = _storage._device else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      }()
      case .u2F?: try {
        guard case .u2F(let v)? = _storage._device else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      }()
      case .webauthn?: try {
        guard case .webauthn(let v)? = _storage._device else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      }()
      case .sso?: try {
        guard case .sso(let v)? = _storage._device else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      }()
      case .browser?: try {
        guard case .browser(let v)? = _storage._device else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      }()
      case nil: break
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Types_MFADevice, rhs: Types_MFADevice) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._kind != rhs_storage._kind {return false}
        if _storage._subKind != rhs_storage._subKind {return false}
        if _storage._version != rhs_storage._version {return false}
        if _storage._metadata != rhs_storage._metadata {return false}
        if _storage._id != rhs_storage._id {return false}
        if _storage._addedAt != rhs_storage._addedAt {return false}
        if _storage._lastUsed != rhs_storage._lastUsed {return false}
        if _storage._device != rhs_storage._device {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Types_TOTPDevice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TOTPDevice"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Types_TOTPDevice, rhs: Types_TOTPDevice) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Types_U2FDevice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".U2FDevice"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}key_handle\0\u{3}pub_key\0\u{1}counter\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.keyHandle) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.pubKey) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.counter) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.keyHandle.isEmpty {
      try visitor.visitSingularBytesField(value: self.keyHandle, fieldNumber: 1)
    }
    if !self.pubKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.pubKey, fieldNumber: 2)
    }
    if self.counter != 0 {
      try visitor.visitSingularUInt32Field(value: self.counter, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Types_U2FDevice, rhs: Types_U2FDevice) -> Bool {
    if lhs.keyHandle != rhs.keyHandle {return false}
    if lhs.pubKey != rhs.pubKey {return false}
    if lhs.counter != rhs.counter {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Types_WebauthnDevice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WebauthnDevice"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}credential_id\0\u{3}public_key_cbor\0\u{3}attestation_type\0\u{1}aaguid\0\u{3}signature_counter\0\u{3}attestation_object\0\u{3}resident_key\0\u{3}credential_rp_id\0\u{3}credential_backup_eligible\0\u{3}credential_backed_up\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.credentialID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.publicKeyCbor) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.attestationType) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.aaguid) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.signatureCounter) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self.attestationObject) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.residentKey) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.credentialRpID) }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._credentialBackupEligible) }()
      case 10: try { try decoder.decodeSingularMessageField(value: &self._credentialBackedUp) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.credentialID.isEmpty {
      try visitor.visitSingularBytesField(value: self.credentialID, fieldNumber: 1)
    }
    if !self.publicKeyCbor.isEmpty {
      try visitor.visitSingularBytesField(value: self.publicKeyCbor, fieldNumber: 2)
    }
    if !self.attestationType.isEmpty {
      try visitor.visitSingularStringField(value: self.attestationType, fieldNumber: 3)
    }
    if !self.aaguid.isEmpty {
      try visitor.visitSingularBytesField(value: self.aaguid, fieldNumber: 4)
    }
    if self.signatureCounter != 0 {
      try visitor.visitSingularUInt32Field(value: self.signatureCounter, fieldNumber: 5)
    }
    if !self.attestationObject.isEmpty {
      try visitor.visitSingularBytesField(value: self.attestationObject, fieldNumber: 6)
    }
    if self.residentKey != false {
      try visitor.visitSingularBoolField(value: self.residentKey, fieldNumber: 7)
    }
    if !self.credentialRpID.isEmpty {
      try visitor.visitSingularStringField(value: self.credentialRpID, fieldNumber: 8)
    }
    try { if let v = self._credentialBackupEligible {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._credentialBackedUp {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Types_WebauthnDevice, rhs: Types_WebauthnDevice) -> Bool {
    if lhs.credentialID != rhs.credentialID {return false}
    if lhs.publicKeyCbor != rhs.publicKeyCbor {return false}
    if lhs.attestationType != rhs.attestationType {return false}
    if lhs.aaguid != rhs.aaguid {return false}
    if lhs.signatureCounter != rhs.signatureCounter {return false}
    if lhs.attestationObject != rhs.attestationObject {return false}
    if lhs.residentKey != rhs.residentKey {return false}
    if lhs.credentialRpID != rhs.credentialRpID {return false}
    if lhs._credentialBackupEligible != rhs._credentialBackupEligible {return false}
    if lhs._credentialBackedUp != rhs._credentialBackedUp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Types_SSOMFADevice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SSOMFADevice"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}connector_id\0\u{3}connector_type\0\u{3}display_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.connectorID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.connectorType) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.connectorID.isEmpty {
      try visitor.visitSingularStringField(value: self.connectorID, fieldNumber: 1)
    }
    if !self.connectorType.isEmpty {
      try visitor.visitSingularStringField(value: self.connectorType, fieldNumber: 2)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Types_SSOMFADevice, rhs: Types_SSOMFADevice) -> Bool {
    if lhs.connectorID != rhs.connectorID {return false}
    if lhs.connectorType != rhs.connectorType {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Types_BrowserMFADevice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BrowserMFADevice"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Types_BrowserMFADevice, rhs: Types_BrowserMFADevice) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
