// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: teleport/accesslist/v1/accesslist.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2023 Gravitational, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// ReviewFrequency is the frequency of reviews.
public nonisolated enum Teleport_Accesslist_V1_ReviewFrequency: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case oneMonth // = 1
  case threeMonths // = 3
  case sixMonths // = 6
  case oneYear // = 12
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .oneMonth
    case 3: self = .threeMonths
    case 6: self = .sixMonths
    case 12: self = .oneYear
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .oneMonth: return 1
    case .threeMonths: return 3
    case .sixMonths: return 6
    case .oneYear: return 12
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Teleport_Accesslist_V1_ReviewFrequency] = [
    .unspecified,
    .oneMonth,
    .threeMonths,
    .sixMonths,
    .oneYear,
  ]

}

/// ReviewDayOfMonth is the day of month that reviews will repeat on.
public nonisolated enum Teleport_Accesslist_V1_ReviewDayOfMonth: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case first // = 1
  case fifteenth // = 15
  case last // = 31
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .first
    case 15: self = .fifteenth
    case 31: self = .last
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .first: return 1
    case .fifteenth: return 15
    case .last: return 31
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Teleport_Accesslist_V1_ReviewDayOfMonth] = [
    .unspecified,
    .first,
    .fifteenth,
    .last,
  ]

}

/// MembershipKind represents the different kinds of list membership
public nonisolated enum Teleport_Accesslist_V1_MembershipKind: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// MEMBERSHIP_KIND_UNSPECIFIED represents list members that are of
  /// unknown membership kind, defaulting to being treated as type USER
  case unspecified // = 0

  /// MEMBERSHIP_KIND_USER represents list members that are normal users
  case user // = 1

  /// MEMBERSHIP_KIND_LIST represents list members that are nested Access Lists
  case list // = 2

  /// MEMBERSHIP_KIND_SCOPED_LIST represents list members that are nested scoped Access Lists
  case scopedList // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .user
    case 2: self = .list
    case 3: self = .scopedList
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .user: return 1
    case .list: return 2
    case .scopedList: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Teleport_Accesslist_V1_MembershipKind] = [
    .unspecified,
    .user,
    .list,
    .scopedList,
  ]

}

/// IneligibleStatus describes how the user is ineligible.
public nonisolated enum Teleport_Accesslist_V1_IneligibleStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// INELIGIBLE_STATUS_UNSPECIFIED means eligiblity is unknown.
  case unspecified // = 0

  /// INELIGIBLE_STATUS_ELIGIBLE means checks were done and user met all
  /// requirements.
  case eligible // = 1

  /// INELIGIBLE_STATUS_USER_NOT_EXIST means user was not found in backend.
  case userNotExist // = 2

  /// INELIGIBLE_STATUS_MISSING_REQUIREMENTS means user is missing some
  /// requirements defined by AccessListRequires (fields can be either
  /// ownership_requires or membership_requires)
  case missingRequirements // = 3

  /// INELIGIBLE_STATUS_EXPIRED means user is expired.
  /// Only applicable to members.
  case expired // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .eligible
    case 2: self = .userNotExist
    case 3: self = .missingRequirements
    case 4: self = .expired
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .eligible: return 1
    case .userNotExist: return 2
    case .missingRequirements: return 3
    case .expired: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Teleport_Accesslist_V1_IneligibleStatus] = [
    .unspecified,
    .eligible,
    .userNotExist,
    .missingRequirements,
    .expired,
  ]

}

/// AccessListUserAssignmentType describes the type of membership and/or ownership
/// a user has in an Access List.
public nonisolated enum Teleport_Accesslist_V1_AccessListUserAssignmentType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// ACCESS_LIST_USER_ASSIGNMENT_TYPE_UNSPECIFIED means the user is not an explicit nor an inherited member or owner
  case unspecified // = 0

  /// ACCESS_LIST_USER_ASSIGNMENT_TYPE_EXPLICIT means the user has explicit membership or ownership
  case explicit // = 1

  /// ACCESS_LIST_USER_ASSIGNMENT_TYPE_INHERITED means the user has inherited membership or ownership
  case inherited // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .explicit
    case 2: self = .inherited
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .explicit: return 1
    case .inherited: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Teleport_Accesslist_V1_AccessListUserAssignmentType] = [
    .unspecified,
    .explicit,
    .inherited,
  ]

}

/// AccessList describes the basic building block of access grants, which are
/// similar to access requests but for longer lived permissions that need to be
/// regularly audited.
public nonisolated struct Teleport_Accesslist_V1_AccessList: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// header is the header for the resource.
  public var header: Teleport_Header_V1_ResourceHeader {
    get {_storage._header ?? Teleport_Header_V1_ResourceHeader()}
    set {_uniqueStorage()._header = newValue}
  }
  /// Returns true if `header` has been explicitly set.
  public var hasHeader: Bool {_storage._header != nil}
  /// Clears the value of `header`. Subsequent reads from it will return its default value.
  public mutating func clearHeader() {_uniqueStorage()._header = nil}

  /// spec is the specification for the Access List.
  public var spec: Teleport_Accesslist_V1_AccessListSpec {
    get {_storage._spec ?? Teleport_Accesslist_V1_AccessListSpec()}
    set {_uniqueStorage()._spec = newValue}
  }
  /// Returns true if `spec` has been explicitly set.
  public var hasSpec: Bool {_storage._spec != nil}
  /// Clears the value of `spec`. Subsequent reads from it will return its default value.
  public mutating func clearSpec() {_uniqueStorage()._spec = nil}

  /// status contains dynamically calculated fields.
  public var status: Teleport_Accesslist_V1_AccessListStatus {
    get {_storage._status ?? Teleport_Accesslist_V1_AccessListStatus()}
    set {_uniqueStorage()._status = newValue}
  }
  /// Returns true if `status` has been explicitly set.
  public var hasStatus: Bool {_storage._status != nil}
  /// Clears the value of `status`. Subsequent reads from it will return its default value.
  public mutating func clearStatus() {_uniqueStorage()._status = nil}

  /// scope is the scope of the Access List.
  public var scope: String {
    get {_storage._scope}
    set {_uniqueStorage()._scope = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// AccessListSpec is the specification for an Access List.
public nonisolated struct Teleport_Accesslist_V1_AccessListSpec: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// description is an optional plaintext description of the Access List.
  public var description_p: String {
    get {_storage._description_p}
    set {_uniqueStorage()._description_p = newValue}
  }

  /// owners is a list of owners of the Access List.
  public var owners: [Teleport_Accesslist_V1_AccessListOwner] {
    get {_storage._owners}
    set {_uniqueStorage()._owners = newValue}
  }

  /// audit describes the frequency that this Access List must be audited.
  public var audit: Teleport_Accesslist_V1_AccessListAudit {
    get {_storage._audit ?? Teleport_Accesslist_V1_AccessListAudit()}
    set {_uniqueStorage()._audit = newValue}
  }
  /// Returns true if `audit` has been explicitly set.
  public var hasAudit: Bool {_storage._audit != nil}
  /// Clears the value of `audit`. Subsequent reads from it will return its default value.
  public mutating func clearAudit() {_uniqueStorage()._audit = nil}

  /// membership_requires describes the requirements for a user to be a member of
  /// the Access List. For a membership to an Access List to be effective, the
  /// user must meet the requirements of Membership_requires and must be in the
  /// members list.
  public var membershipRequires: Teleport_Accesslist_V1_AccessListRequires {
    get {_storage._membershipRequires ?? Teleport_Accesslist_V1_AccessListRequires()}
    set {_uniqueStorage()._membershipRequires = newValue}
  }
  /// Returns true if `membershipRequires` has been explicitly set.
  public var hasMembershipRequires: Bool {_storage._membershipRequires != nil}
  /// Clears the value of `membershipRequires`. Subsequent reads from it will return its default value.
  public mutating func clearMembershipRequires() {_uniqueStorage()._membershipRequires = nil}

  /// ownership_requires describes the requirements for a user to be an owner of
  /// the Access List. For ownership of an Access List to be effective, the user
  /// must meet the requirements of ownership_requires and must be in the owners
  /// list.
  public var ownershipRequires: Teleport_Accesslist_V1_AccessListRequires {
    get {_storage._ownershipRequires ?? Teleport_Accesslist_V1_AccessListRequires()}
    set {_uniqueStorage()._ownershipRequires = newValue}
  }
  /// Returns true if `ownershipRequires` has been explicitly set.
  public var hasOwnershipRequires: Bool {_storage._ownershipRequires != nil}
  /// Clears the value of `ownershipRequires`. Subsequent reads from it will return its default value.
  public mutating func clearOwnershipRequires() {_uniqueStorage()._ownershipRequires = nil}

  /// grants describes the access granted by membership to this Access List.
  public var grants: Teleport_Accesslist_V1_AccessListGrants {
    get {_storage._grants ?? Teleport_Accesslist_V1_AccessListGrants()}
    set {_uniqueStorage()._grants = newValue}
  }
  /// Returns true if `grants` has been explicitly set.
  public var hasGrants: Bool {_storage._grants != nil}
  /// Clears the value of `grants`. Subsequent reads from it will return its default value.
  public mutating func clearGrants() {_uniqueStorage()._grants = nil}

  /// title is a plaintext short description of the Access List.
  public var title: String {
    get {_storage._title}
    set {_uniqueStorage()._title = newValue}
  }

  /// owner_grants describes the access granted by owners to this Access List.
  public var ownerGrants: Teleport_Accesslist_V1_AccessListGrants {
    get {_storage._ownerGrants ?? Teleport_Accesslist_V1_AccessListGrants()}
    set {_uniqueStorage()._ownerGrants = newValue}
  }
  /// Returns true if `ownerGrants` has been explicitly set.
  public var hasOwnerGrants: Bool {_storage._ownerGrants != nil}
  /// Clears the value of `ownerGrants`. Subsequent reads from it will return its default value.
  public mutating func clearOwnerGrants() {_uniqueStorage()._ownerGrants = nil}

  /// type can be an empty string which denotes a regular Access List, "scim" which represents
  /// an Access List created from SCIM group or "static" for Access Lists managed by IaC
  /// tools.
  public var type: String {
    get {_storage._type}
    set {_uniqueStorage()._type = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// AccessListOwner is an owner of an Access List.
public nonisolated struct Teleport_Accesslist_V1_AccessListOwner: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// name is the name of the owner, depending on MembershipKind:
  /// MEMBERSHIP_KIND_USER: the username of the owner.
  /// MEMBERSHIP_KIND_LIST: the name of the owner Access List.
  /// MEMBERSHIP_KIND_SCOPED_LIST: the scope-qualified name of the owner Access List.
  public var name: String = String()

  /// description is the plaintext description of the owner and why they are an
  /// owner.
  public var description_p: String = String()

  /// ineligible_status describes if this owner is eligible or not
  /// and if not, describes how they're lacking eligibility.
  public var ineligibleStatus: Teleport_Accesslist_V1_IneligibleStatus = .unspecified

  /// membership_kind describes the type of membership, either
  /// `MEMBERSHIP_KIND_USER` or `MEMBERSHIP_KIND_LIST` or `MEMBERSHIP_KIND_SCOPED_LIST`.
  public var membershipKind: Teleport_Accesslist_V1_MembershipKind = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// AccessListAudit describes the audit configuration for an Access List.
public nonisolated struct Teleport_Accesslist_V1_AccessListAudit: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// next_audit_date is when the next audit date should be done by.
  public var nextAuditDate: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_nextAuditDate ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_nextAuditDate = newValue}
  }
  /// Returns true if `nextAuditDate` has been explicitly set.
  public var hasNextAuditDate: Bool {self._nextAuditDate != nil}
  /// Clears the value of `nextAuditDate`. Subsequent reads from it will return its default value.
  public mutating func clearNextAuditDate() {self._nextAuditDate = nil}

  /// recurrence is the recurrence definition
  public var recurrence: Teleport_Accesslist_V1_Recurrence {
    get {_recurrence ?? Teleport_Accesslist_V1_Recurrence()}
    set {_recurrence = newValue}
  }
  /// Returns true if `recurrence` has been explicitly set.
  public var hasRecurrence: Bool {self._recurrence != nil}
  /// Clears the value of `recurrence`. Subsequent reads from it will return its default value.
  public mutating func clearRecurrence() {self._recurrence = nil}

  /// notifications is the configuration for notifying users.
  public var notifications: Teleport_Accesslist_V1_Notifications {
    get {_notifications ?? Teleport_Accesslist_V1_Notifications()}
    set {_notifications = newValue}
  }
  /// Returns true if `notifications` has been explicitly set.
  public var hasNotifications: Bool {self._notifications != nil}
  /// Clears the value of `notifications`. Subsequent reads from it will return its default value.
  public mutating func clearNotifications() {self._notifications = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _nextAuditDate: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _recurrence: Teleport_Accesslist_V1_Recurrence? = nil
  fileprivate var _notifications: Teleport_Accesslist_V1_Notifications? = nil
}

/// Recurrence is the definition for when reviews will be scheduled.
public nonisolated struct Teleport_Accesslist_V1_Recurrence: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// frequency is the frequency of reviews. This represents the period in months
  /// between two reviews.
  /// Supported values are 0, 1, 3, 6, and 12.
  public var frequency: Teleport_Accesslist_V1_ReviewFrequency = .unspecified

  /// day_of_month is the day of month that reviews will be scheduled on.
  /// Supported values are 0, 1, 15, and 31.
  public var dayOfMonth: Teleport_Accesslist_V1_ReviewDayOfMonth = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Notifications contains the configuration for notifying users of a nearing
/// next audit date.
public nonisolated struct Teleport_Accesslist_V1_Notifications: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// start specifies when to start notifying users that the next audit date is
  /// coming up.
  public var start: SwiftProtobuf.Google_Protobuf_Duration {
    get {_start ?? SwiftProtobuf.Google_Protobuf_Duration()}
    set {_start = newValue}
  }
  /// Returns true if `start` has been explicitly set.
  public var hasStart: Bool {self._start != nil}
  /// Clears the value of `start`. Subsequent reads from it will return its default value.
  public mutating func clearStart() {self._start = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _start: SwiftProtobuf.Google_Protobuf_Duration? = nil
}

/// AccessListRequires describes a requirement section for an Access List. A user
/// must meet the following criteria to obtain the specific access to the list.
public nonisolated struct Teleport_Accesslist_V1_AccessListRequires: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// roles are the user roles that must be present for the user to obtain
  /// access.
  public var roles: [String] = []

  /// traits are the traits that must be present for the user to obtain access.
  public var traits: [Teleport_Trait_V1_Trait] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// AccessListGrants describes what access is granted by membership to the Access
/// List.
public nonisolated struct Teleport_Accesslist_V1_AccessListGrants: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// roles are the names of roles to be granted to users.
  public var roles: [String] = []

  /// traits are the traits to be granted to users.
  public var traits: [Teleport_Trait_V1_Trait] = []

  /// scoped_roles are scoped roles to be granted to users.
  public var scopedRoles: [Teleport_Accesslist_V1_ScopedRoleGrant] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// ScopedRoleGrant describes a scoped role granted at a specific scope.
public nonisolated struct Teleport_Accesslist_V1_ScopedRoleGrant: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// role is the scope-qualified name of the scoped role to be granted.
  public var role: String = String()

  /// scope is the scope the role will be granted at. It must be an assignable
  /// scope of the role.
  public var scope: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// UserDisplay contains display values derived from a user. An empty message
/// means the user has no primary/secondary distinct from the username; the
/// absence of this message means the user was not found.
public nonisolated struct Teleport_Accesslist_V1_UserDisplay: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// primary is a human-readable display name when distinct from username.
  public var primary: String = String()

  /// secondary is supporting display context when distinct from username.
  public var secondary: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Member describes a member of an Access List.
public nonisolated struct Teleport_Accesslist_V1_Member: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// header is the header for the resource.
  public var header: Teleport_Header_V1_ResourceHeader {
    get {_storage._header ?? Teleport_Header_V1_ResourceHeader()}
    set {_uniqueStorage()._header = newValue}
  }
  /// Returns true if `header` has been explicitly set.
  public var hasHeader: Bool {_storage._header != nil}
  /// Clears the value of `header`. Subsequent reads from it will return its default value.
  public mutating func clearHeader() {_uniqueStorage()._header = nil}

  /// spec is the specification for the Access List member.
  public var spec: Teleport_Accesslist_V1_MemberSpec {
    get {_storage._spec ?? Teleport_Accesslist_V1_MemberSpec()}
    set {_uniqueStorage()._spec = newValue}
  }
  /// Returns true if `spec` has been explicitly set.
  public var hasSpec: Bool {_storage._spec != nil}
  /// Clears the value of `spec`. Subsequent reads from it will return its default value.
  public mutating func clearSpec() {_uniqueStorage()._spec = nil}

  /// scope is the scope of the Access List member, it must be equal to the
  /// scope of the parent Access List.
  public var scope: String {
    get {_storage._scope}
    set {_uniqueStorage()._scope = newValue}
  }

  /// status contains dynamically calculated fields.
  public var status: Teleport_Accesslist_V1_MemberStatus {
    get {_storage._status ?? Teleport_Accesslist_V1_MemberStatus()}
    set {_uniqueStorage()._status = newValue}
  }
  /// Returns true if `status` has been explicitly set.
  public var hasStatus: Bool {_storage._status != nil}
  /// Clears the value of `status`. Subsequent reads from it will return its default value.
  public mutating func clearStatus() {_uniqueStorage()._status = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// MemberStatus contains dynamic fields calculated during retrieval.
public nonisolated struct Teleport_Accesslist_V1_MemberStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// display contains display values for the member user.
  public var display: Teleport_Accesslist_V1_UserDisplay {
    get {_display ?? Teleport_Accesslist_V1_UserDisplay()}
    set {_display = newValue}
  }
  /// Returns true if `display` has been explicitly set.
  public var hasDisplay: Bool {self._display != nil}
  /// Clears the value of `display`. Subsequent reads from it will return its default value.
  public mutating func clearDisplay() {self._display = nil}

  /// added_by_display contains display values for the user that added the member.
  public var addedByDisplay: Teleport_Accesslist_V1_UserDisplay {
    get {_addedByDisplay ?? Teleport_Accesslist_V1_UserDisplay()}
    set {_addedByDisplay = newValue}
  }
  /// Returns true if `addedByDisplay` has been explicitly set.
  public var hasAddedByDisplay: Bool {self._addedByDisplay != nil}
  /// Clears the value of `addedByDisplay`. Subsequent reads from it will return its default value.
  public mutating func clearAddedByDisplay() {self._addedByDisplay = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _display: Teleport_Accesslist_V1_UserDisplay? = nil
  fileprivate var _addedByDisplay: Teleport_Accesslist_V1_UserDisplay? = nil
}

/// ReviewStatus contains dynamic fields calculated during retrieval.
public nonisolated struct Teleport_Accesslist_V1_ReviewStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// reviewer_displays maps reviewer usernames to read-time display values
  /// derived from the user resource.
  public var reviewerDisplays: Dictionary<String,Teleport_Accesslist_V1_UserDisplay> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// MemberSpec is the specification for an Access List member.
public nonisolated struct Teleport_Accesslist_V1_MemberSpec: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// associated Access List
  public var accessList: String = String()

  /// name is the name of the member of the Access List, depending on MembershipKind:
  /// MEMBERSHIP_KIND_USER: the username of the member.
  /// MEMBERSHIP_KIND_LIST: the name of the member Access List.
  /// MEMBERSHIP_KIND_SCOPED_LIST: the scope-qualified name of the member scope Access List.
  public var name: String = String()

  /// joined is when the user joined the Access List.
  public var joined: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_joined ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_joined = newValue}
  }
  /// Returns true if `joined` has been explicitly set.
  public var hasJoined: Bool {self._joined != nil}
  /// Clears the value of `joined`. Subsequent reads from it will return its default value.
  public mutating func clearJoined() {self._joined = nil}

  /// expires is when the user's membership to the Access List expires.
  public var expires: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_expires ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_expires = newValue}
  }
  /// Returns true if `expires` has been explicitly set.
  public var hasExpires: Bool {self._expires != nil}
  /// Clears the value of `expires`. Subsequent reads from it will return its default value.
  public mutating func clearExpires() {self._expires = nil}

  /// reason is the reason this user was added to the Access List.
  public var reason: String = String()

  /// added_by is the user that added this user to the Access List.
  public var addedBy: String = String()

  /// ineligible_status describes if this member is eligible or not
  /// and if not, describes how they're lacking eligibility.
  public var ineligibleStatus: Teleport_Accesslist_V1_IneligibleStatus = .unspecified

  /// membership_kind describes the type of membership, either
  /// `MEMBERSHIP_KIND_USER` or `MEMBERSHIP_KIND_LIST` or `MEMBERSHIP_KIND_SCOPED_LIST`.
  public var membershipKind: Teleport_Accesslist_V1_MembershipKind = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _joined: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _expires: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// Review is a review of an Access List.
public nonisolated struct Teleport_Accesslist_V1_Review: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// header is the header for the resource.
  public var header: Teleport_Header_V1_ResourceHeader {
    get {_storage._header ?? Teleport_Header_V1_ResourceHeader()}
    set {_uniqueStorage()._header = newValue}
  }
  /// Returns true if `header` has been explicitly set.
  public var hasHeader: Bool {_storage._header != nil}
  /// Clears the value of `header`. Subsequent reads from it will return its default value.
  public mutating func clearHeader() {_uniqueStorage()._header = nil}

  /// spec is the specification for the Access List review.
  public var spec: Teleport_Accesslist_V1_ReviewSpec {
    get {_storage._spec ?? Teleport_Accesslist_V1_ReviewSpec()}
    set {_uniqueStorage()._spec = newValue}
  }
  /// Returns true if `spec` has been explicitly set.
  public var hasSpec: Bool {_storage._spec != nil}
  /// Clears the value of `spec`. Subsequent reads from it will return its default value.
  public mutating func clearSpec() {_uniqueStorage()._spec = nil}

  /// scope is the scope of the Access List review. It must be equal to the
  /// scope of the reviewed Access List.
  public var scope: String {
    get {_storage._scope}
    set {_uniqueStorage()._scope = newValue}
  }

  /// status contains dynamically calculated fields.
  public var status: Teleport_Accesslist_V1_ReviewStatus {
    get {_storage._status ?? Teleport_Accesslist_V1_ReviewStatus()}
    set {_uniqueStorage()._status = newValue}
  }
  /// Returns true if `status` has been explicitly set.
  public var hasStatus: Bool {_storage._status != nil}
  /// Clears the value of `status`. Subsequent reads from it will return its default value.
  public mutating func clearStatus() {_uniqueStorage()._status = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// ReviewSpec is the specification for an Access List review.
public nonisolated struct Teleport_Accesslist_V1_ReviewSpec: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// access_list is the name of the Access List that this review is for.
  /// If the review is scoped, this is the scope-qualified name of the reviewed
  /// scoped Access List.
  public var accessList: String = String()

  /// reviewers are the users who performed the review.
  public var reviewers: [String] = []

  /// review_date is the date that this review was created.
  public var reviewDate: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_reviewDate ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_reviewDate = newValue}
  }
  /// Returns true if `reviewDate` has been explicitly set.
  public var hasReviewDate: Bool {self._reviewDate != nil}
  /// Clears the value of `reviewDate`. Subsequent reads from it will return its default value.
  public mutating func clearReviewDate() {self._reviewDate = nil}

  /// notes is an optional plaintext attached to the review that can be used by
  /// the review for arbitrary note taking on the review.
  public var notes: String = String()

  /// changes are the changes made as part of the review.
  public var changes: Teleport_Accesslist_V1_ReviewChanges {
    get {_changes ?? Teleport_Accesslist_V1_ReviewChanges()}
    set {_changes = newValue}
  }
  /// Returns true if `changes` has been explicitly set.
  public var hasChanges: Bool {self._changes != nil}
  /// Clears the value of `changes`. Subsequent reads from it will return its default value.
  public mutating func clearChanges() {self._changes = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _reviewDate: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _changes: Teleport_Accesslist_V1_ReviewChanges? = nil
}

/// ReviewChanges are the changes that were made as part of the review.
public nonisolated struct Teleport_Accesslist_V1_ReviewChanges: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// membership_requirements_changed is populated if the requirements were
  /// changed as part of this review.
  public var membershipRequirementsChanged: Teleport_Accesslist_V1_AccessListRequires {
    get {_membershipRequirementsChanged ?? Teleport_Accesslist_V1_AccessListRequires()}
    set {_membershipRequirementsChanged = newValue}
  }
  /// Returns true if `membershipRequirementsChanged` has been explicitly set.
  public var hasMembershipRequirementsChanged: Bool {self._membershipRequirementsChanged != nil}
  /// Clears the value of `membershipRequirementsChanged`. Subsequent reads from it will return its default value.
  public mutating func clearMembershipRequirementsChanged() {self._membershipRequirementsChanged = nil}

  /// removed_members contains the members that were removed as part of this
  /// review.
  public var removedMembers: [String] = []

  /// review_frequency_changed is populated if the review frequency has changed.
  public var reviewFrequencyChanged: Teleport_Accesslist_V1_ReviewFrequency = .unspecified

  /// review_day_of_month_changed is populated if the review day of month has
  /// changed.
  public var reviewDayOfMonthChanged: Teleport_Accesslist_V1_ReviewDayOfMonth = .unspecified

  /// scoped_removed_members contains the scope-qualified names of members that
  /// were removed as part of this review.
  public var scopedRemovedMembers: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _membershipRequirementsChanged: Teleport_Accesslist_V1_AccessListRequires? = nil
}

/// CurrentUserAssignments describes the current user's ownership and membership status in the Access List.
public nonisolated struct Teleport_Accesslist_V1_CurrentUserAssignments: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// ownership_type represents the current user's ownership type (explicit, inherited, or none) in the Access List.
  public var ownershipType: Teleport_Accesslist_V1_AccessListUserAssignmentType = .unspecified

  /// membership_type represents the current user's membership type (explicit, inherited, or none) in the Access List.
  public var membershipType: Teleport_Accesslist_V1_AccessListUserAssignmentType = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// UserAssignments describes the requested user's ownership and membership assignment types in the Access List.
public nonisolated struct Teleport_Accesslist_V1_UserAssignments: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// ownership_type represents the requested user's ownership type (explicit, inherited, or none) in the Access List.
  public var ownershipType: Teleport_Accesslist_V1_AccessListUserAssignmentType = .unspecified

  /// membership_type represents the requested user's membership type (explicit, inherited, or none) in the Access List.
  public var membershipType: Teleport_Accesslist_V1_AccessListUserAssignmentType = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// AccessListStatus contains dynamic fields calculated during retrieval.
public nonisolated struct Teleport_Accesslist_V1_AccessListStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// member_count is the number of members in the Access List.
  public var memberCount: UInt32 {
    get {_memberCount ?? 0}
    set {_memberCount = newValue}
  }
  /// Returns true if `memberCount` has been explicitly set.
  public var hasMemberCount: Bool {self._memberCount != nil}
  /// Clears the value of `memberCount`. Subsequent reads from it will return its default value.
  public mutating func clearMemberCount() {self._memberCount = nil}

  /// member_list_count is the number of nested list members in the Access List.
  public var memberListCount: UInt32 {
    get {_memberListCount ?? 0}
    set {_memberListCount = newValue}
  }
  /// Returns true if `memberListCount` has been explicitly set.
  public var hasMemberListCount: Bool {self._memberListCount != nil}
  /// Clears the value of `memberListCount`. Subsequent reads from it will return its default value.
  public mutating func clearMemberListCount() {self._memberListCount = nil}

  /// owner_of describes Access Lists where this Access List is an explicit owner.
  public var ownerOf: [String] = []

  /// member_of describes Access Lists where this Access List is an explicit member.
  public var memberOf: [String] = []

  /// current_user_assignments describes the current user's ownership and membership status in the Access List.
  public var currentUserAssignments: Teleport_Accesslist_V1_CurrentUserAssignments {
    get {_currentUserAssignments ?? Teleport_Accesslist_V1_CurrentUserAssignments()}
    set {_currentUserAssignments = newValue}
  }
  /// Returns true if `currentUserAssignments` has been explicitly set.
  public var hasCurrentUserAssignments: Bool {self._currentUserAssignments != nil}
  /// Clears the value of `currentUserAssignments`. Subsequent reads from it will return its default value.
  public mutating func clearCurrentUserAssignments() {self._currentUserAssignments = nil}

  /// user_assignments describes the requested user's ownership and membership assignment types in the Access List.
  public var userAssignments: Teleport_Accesslist_V1_UserAssignments {
    get {_userAssignments ?? Teleport_Accesslist_V1_UserAssignments()}
    set {_userAssignments = newValue}
  }
  /// Returns true if `userAssignments` has been explicitly set.
  public var hasUserAssignments: Bool {self._userAssignments != nil}
  /// Clears the value of `userAssignments`. Subsequent reads from it will return its default value.
  public mutating func clearUserAssignments() {self._userAssignments = nil}

  /// scoped_owner_of describes scoped Access Lists where this Access List is an explicit owner.
  /// Each item is the scope-qualified name of the owned scoped Access List.
  public var scopedOwnerOf: [String] = []

  /// scoped_member_of describes scoped Access Lists where this Access List is an explicit member.
  /// Each item is the scope-qualified name of the parent scoped Access List.
  public var scopedMemberOf: [String] = []

  /// owner_displays contains display values for owners, keyed by owner username.
  public var ownerDisplays: Dictionary<String,Teleport_Accesslist_V1_UserDisplay> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _memberCount: UInt32? = nil
  fileprivate var _memberListCount: UInt32? = nil
  fileprivate var _currentUserAssignments: Teleport_Accesslist_V1_CurrentUserAssignments? = nil
  fileprivate var _userAssignments: Teleport_Accesslist_V1_UserAssignments? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "teleport.accesslist.v1"

nonisolated extension Teleport_Accesslist_V1_ReviewFrequency: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0REVIEW_FREQUENCY_UNSPECIFIED\0\u{1}REVIEW_FREQUENCY_ONE_MONTH\0\u{2}\u{2}REVIEW_FREQUENCY_THREE_MONTHS\0\u{2}\u{3}REVIEW_FREQUENCY_SIX_MONTHS\0\u{2}\u{6}REVIEW_FREQUENCY_ONE_YEAR\0")
}

nonisolated extension Teleport_Accesslist_V1_ReviewDayOfMonth: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0REVIEW_DAY_OF_MONTH_UNSPECIFIED\0\u{1}REVIEW_DAY_OF_MONTH_FIRST\0\u{2}\u{e}REVIEW_DAY_OF_MONTH_FIFTEENTH\0\u{2}\u{10}REVIEW_DAY_OF_MONTH_LAST\0")
}

nonisolated extension Teleport_Accesslist_V1_MembershipKind: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0MEMBERSHIP_KIND_UNSPECIFIED\0\u{1}MEMBERSHIP_KIND_USER\0\u{1}MEMBERSHIP_KIND_LIST\0\u{1}MEMBERSHIP_KIND_SCOPED_LIST\0")
}

nonisolated extension Teleport_Accesslist_V1_IneligibleStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0INELIGIBLE_STATUS_UNSPECIFIED\0\u{1}INELIGIBLE_STATUS_ELIGIBLE\0\u{1}INELIGIBLE_STATUS_USER_NOT_EXIST\0\u{1}INELIGIBLE_STATUS_MISSING_REQUIREMENTS\0\u{1}INELIGIBLE_STATUS_EXPIRED\0")
}

nonisolated extension Teleport_Accesslist_V1_AccessListUserAssignmentType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ACCESS_LIST_USER_ASSIGNMENT_TYPE_UNSPECIFIED\0\u{1}ACCESS_LIST_USER_ASSIGNMENT_TYPE_EXPLICIT\0\u{1}ACCESS_LIST_USER_ASSIGNMENT_TYPE_INHERITED\0")
}

nonisolated extension Teleport_Accesslist_V1_AccessList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AccessList"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}header\0\u{1}spec\0\u{1}status\0\u{1}scope\0")

  fileprivate class _StorageClass {
    var _header: Teleport_Header_V1_ResourceHeader? = nil
    var _spec: Teleport_Accesslist_V1_AccessListSpec? = nil
    var _status: Teleport_Accesslist_V1_AccessListStatus? = nil
    var _scope: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _header = source._header
      _spec = source._spec
      _status = source._status
      _scope = source._scope
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._header) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._spec) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._status) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._scope) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._header {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._spec {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._status {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      if !_storage._scope.isEmpty {
        try visitor.visitSingularStringField(value: _storage._scope, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_AccessList, rhs: Teleport_Accesslist_V1_AccessList) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._header != rhs_storage._header {return false}
        if _storage._spec != rhs_storage._spec {return false}
        if _storage._status != rhs_storage._status {return false}
        if _storage._scope != rhs_storage._scope {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_AccessListSpec: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AccessListSpec"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}description\0\u{1}owners\0\u{1}audit\0\u{3}membership_requires\0\u{3}ownership_requires\0\u{1}grants\0\u{2}\u{2}title\0\u{4}\u{3}owner_grants\0\u{1}type\0\u{b}members\0\u{b}membership\0\u{b}ownership\0\u{c}\u{7}\u{1}\u{c}\u{9}\u{1}\u{c}\u{a}\u{1}")

  fileprivate class _StorageClass {
    var _description_p: String = String()
    var _owners: [Teleport_Accesslist_V1_AccessListOwner] = []
    var _audit: Teleport_Accesslist_V1_AccessListAudit? = nil
    var _membershipRequires: Teleport_Accesslist_V1_AccessListRequires? = nil
    var _ownershipRequires: Teleport_Accesslist_V1_AccessListRequires? = nil
    var _grants: Teleport_Accesslist_V1_AccessListGrants? = nil
    var _title: String = String()
    var _ownerGrants: Teleport_Accesslist_V1_AccessListGrants? = nil
    var _type: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _description_p = source._description_p
      _owners = source._owners
      _audit = source._audit
      _membershipRequires = source._membershipRequires
      _ownershipRequires = source._ownershipRequires
      _grants = source._grants
      _title = source._title
      _ownerGrants = source._ownerGrants
      _type = source._type
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._description_p) }()
        case 2: try { try decoder.decodeRepeatedMessageField(value: &_storage._owners) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._audit) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._membershipRequires) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._ownershipRequires) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._grants) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._title) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._ownerGrants) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._type) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._description_p.isEmpty {
        try visitor.visitSingularStringField(value: _storage._description_p, fieldNumber: 1)
      }
      if !_storage._owners.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._owners, fieldNumber: 2)
      }
      try { if let v = _storage._audit {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._membershipRequires {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._ownershipRequires {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._grants {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      if !_storage._title.isEmpty {
        try visitor.visitSingularStringField(value: _storage._title, fieldNumber: 8)
      }
      try { if let v = _storage._ownerGrants {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
      if !_storage._type.isEmpty {
        try visitor.visitSingularStringField(value: _storage._type, fieldNumber: 12)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_AccessListSpec, rhs: Teleport_Accesslist_V1_AccessListSpec) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._description_p != rhs_storage._description_p {return false}
        if _storage._owners != rhs_storage._owners {return false}
        if _storage._audit != rhs_storage._audit {return false}
        if _storage._membershipRequires != rhs_storage._membershipRequires {return false}
        if _storage._ownershipRequires != rhs_storage._ownershipRequires {return false}
        if _storage._grants != rhs_storage._grants {return false}
        if _storage._title != rhs_storage._title {return false}
        if _storage._ownerGrants != rhs_storage._ownerGrants {return false}
        if _storage._type != rhs_storage._type {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_AccessListOwner: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AccessListOwner"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}description\0\u{3}ineligible_status\0\u{3}membership_kind\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.ineligibleStatus) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.membershipKind) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 2)
    }
    if self.ineligibleStatus != .unspecified {
      try visitor.visitSingularEnumField(value: self.ineligibleStatus, fieldNumber: 3)
    }
    if self.membershipKind != .unspecified {
      try visitor.visitSingularEnumField(value: self.membershipKind, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_AccessListOwner, rhs: Teleport_Accesslist_V1_AccessListOwner) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs.ineligibleStatus != rhs.ineligibleStatus {return false}
    if lhs.membershipKind != rhs.membershipKind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_AccessListAudit: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AccessListAudit"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{2}next_audit_date\0\u{1}recurrence\0\u{1}notifications\0\u{b}frequency\0\u{c}\u{1}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularMessageField(value: &self._nextAuditDate) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._recurrence) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._notifications) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._nextAuditDate {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._recurrence {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._notifications {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_AccessListAudit, rhs: Teleport_Accesslist_V1_AccessListAudit) -> Bool {
    if lhs._nextAuditDate != rhs._nextAuditDate {return false}
    if lhs._recurrence != rhs._recurrence {return false}
    if lhs._notifications != rhs._notifications {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_Recurrence: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Recurrence"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}frequency\0\u{3}day_of_month\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.frequency) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.dayOfMonth) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.frequency != .unspecified {
      try visitor.visitSingularEnumField(value: self.frequency, fieldNumber: 1)
    }
    if self.dayOfMonth != .unspecified {
      try visitor.visitSingularEnumField(value: self.dayOfMonth, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_Recurrence, rhs: Teleport_Accesslist_V1_Recurrence) -> Bool {
    if lhs.frequency != rhs.frequency {return false}
    if lhs.dayOfMonth != rhs.dayOfMonth {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_Notifications: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Notifications"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}start\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._start) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._start {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_Notifications, rhs: Teleport_Accesslist_V1_Notifications) -> Bool {
    if lhs._start != rhs._start {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_AccessListRequires: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AccessListRequires"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}roles\0\u{1}traits\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.roles) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.traits) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.roles.isEmpty {
      try visitor.visitRepeatedStringField(value: self.roles, fieldNumber: 1)
    }
    if !self.traits.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.traits, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_AccessListRequires, rhs: Teleport_Accesslist_V1_AccessListRequires) -> Bool {
    if lhs.roles != rhs.roles {return false}
    if lhs.traits != rhs.traits {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_AccessListGrants: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AccessListGrants"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}roles\0\u{1}traits\0\u{3}scoped_roles\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.roles) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.traits) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.scopedRoles) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.roles.isEmpty {
      try visitor.visitRepeatedStringField(value: self.roles, fieldNumber: 1)
    }
    if !self.traits.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.traits, fieldNumber: 2)
    }
    if !self.scopedRoles.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.scopedRoles, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_AccessListGrants, rhs: Teleport_Accesslist_V1_AccessListGrants) -> Bool {
    if lhs.roles != rhs.roles {return false}
    if lhs.traits != rhs.traits {return false}
    if lhs.scopedRoles != rhs.scopedRoles {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_ScopedRoleGrant: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ScopedRoleGrant"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}role\0\u{1}scope\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.role) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.scope) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.role.isEmpty {
      try visitor.visitSingularStringField(value: self.role, fieldNumber: 1)
    }
    if !self.scope.isEmpty {
      try visitor.visitSingularStringField(value: self.scope, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_ScopedRoleGrant, rhs: Teleport_Accesslist_V1_ScopedRoleGrant) -> Bool {
    if lhs.role != rhs.role {return false}
    if lhs.scope != rhs.scope {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_UserDisplay: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UserDisplay"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}primary\0\u{1}secondary\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.primary) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.secondary) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.primary.isEmpty {
      try visitor.visitSingularStringField(value: self.primary, fieldNumber: 1)
    }
    if !self.secondary.isEmpty {
      try visitor.visitSingularStringField(value: self.secondary, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_UserDisplay, rhs: Teleport_Accesslist_V1_UserDisplay) -> Bool {
    if lhs.primary != rhs.primary {return false}
    if lhs.secondary != rhs.secondary {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_Member: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Member"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}header\0\u{1}spec\0\u{1}scope\0\u{1}status\0")

  fileprivate class _StorageClass {
    var _header: Teleport_Header_V1_ResourceHeader? = nil
    var _spec: Teleport_Accesslist_V1_MemberSpec? = nil
    var _scope: String = String()
    var _status: Teleport_Accesslist_V1_MemberStatus? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _header = source._header
      _spec = source._spec
      _scope = source._scope
      _status = source._status
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._header) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._spec) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._scope) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._status) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._header {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._spec {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if !_storage._scope.isEmpty {
        try visitor.visitSingularStringField(value: _storage._scope, fieldNumber: 3)
      }
      try { if let v = _storage._status {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_Member, rhs: Teleport_Accesslist_V1_Member) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._header != rhs_storage._header {return false}
        if _storage._spec != rhs_storage._spec {return false}
        if _storage._scope != rhs_storage._scope {return false}
        if _storage._status != rhs_storage._status {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_MemberStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MemberStatus"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}display\0\u{3}added_by_display\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._display) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._addedByDisplay) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._display {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._addedByDisplay {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_MemberStatus, rhs: Teleport_Accesslist_V1_MemberStatus) -> Bool {
    if lhs._display != rhs._display {return false}
    if lhs._addedByDisplay != rhs._addedByDisplay {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_ReviewStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReviewStatus"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}reviewer_displays\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Teleport_Accesslist_V1_UserDisplay>.self, value: &self.reviewerDisplays) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.reviewerDisplays.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Teleport_Accesslist_V1_UserDisplay>.self, value: self.reviewerDisplays, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_ReviewStatus, rhs: Teleport_Accesslist_V1_ReviewStatus) -> Bool {
    if lhs.reviewerDisplays != rhs.reviewerDisplays {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_MemberSpec: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MemberSpec"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}access_list\0\u{1}name\0\u{1}joined\0\u{1}expires\0\u{1}reason\0\u{3}added_by\0\u{3}ineligible_status\0\u{4}\u{2}membership_kind\0\u{b}membership\0\u{c}\u{8}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.accessList) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._joined) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._expires) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.reason) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.addedBy) }()
      case 7: try { try decoder.decodeSingularEnumField(value: &self.ineligibleStatus) }()
      case 9: try { try decoder.decodeSingularEnumField(value: &self.membershipKind) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.accessList.isEmpty {
      try visitor.visitSingularStringField(value: self.accessList, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    try { if let v = self._joined {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._expires {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if !self.reason.isEmpty {
      try visitor.visitSingularStringField(value: self.reason, fieldNumber: 5)
    }
    if !self.addedBy.isEmpty {
      try visitor.visitSingularStringField(value: self.addedBy, fieldNumber: 6)
    }
    if self.ineligibleStatus != .unspecified {
      try visitor.visitSingularEnumField(value: self.ineligibleStatus, fieldNumber: 7)
    }
    if self.membershipKind != .unspecified {
      try visitor.visitSingularEnumField(value: self.membershipKind, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_MemberSpec, rhs: Teleport_Accesslist_V1_MemberSpec) -> Bool {
    if lhs.accessList != rhs.accessList {return false}
    if lhs.name != rhs.name {return false}
    if lhs._joined != rhs._joined {return false}
    if lhs._expires != rhs._expires {return false}
    if lhs.reason != rhs.reason {return false}
    if lhs.addedBy != rhs.addedBy {return false}
    if lhs.ineligibleStatus != rhs.ineligibleStatus {return false}
    if lhs.membershipKind != rhs.membershipKind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_Review: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Review"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}header\0\u{1}spec\0\u{1}scope\0\u{1}status\0")

  fileprivate class _StorageClass {
    var _header: Teleport_Header_V1_ResourceHeader? = nil
    var _spec: Teleport_Accesslist_V1_ReviewSpec? = nil
    var _scope: String = String()
    var _status: Teleport_Accesslist_V1_ReviewStatus? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _header = source._header
      _spec = source._spec
      _scope = source._scope
      _status = source._status
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._header) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._spec) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._scope) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._status) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._header {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._spec {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if !_storage._scope.isEmpty {
        try visitor.visitSingularStringField(value: _storage._scope, fieldNumber: 3)
      }
      try { if let v = _storage._status {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_Review, rhs: Teleport_Accesslist_V1_Review) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._header != rhs_storage._header {return false}
        if _storage._spec != rhs_storage._spec {return false}
        if _storage._scope != rhs_storage._scope {return false}
        if _storage._status != rhs_storage._status {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_ReviewSpec: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReviewSpec"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}access_list\0\u{1}reviewers\0\u{3}review_date\0\u{1}notes\0\u{1}changes\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.accessList) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.reviewers) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._reviewDate) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.notes) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._changes) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.accessList.isEmpty {
      try visitor.visitSingularStringField(value: self.accessList, fieldNumber: 1)
    }
    if !self.reviewers.isEmpty {
      try visitor.visitRepeatedStringField(value: self.reviewers, fieldNumber: 2)
    }
    try { if let v = self._reviewDate {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.notes.isEmpty {
      try visitor.visitSingularStringField(value: self.notes, fieldNumber: 4)
    }
    try { if let v = self._changes {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_ReviewSpec, rhs: Teleport_Accesslist_V1_ReviewSpec) -> Bool {
    if lhs.accessList != rhs.accessList {return false}
    if lhs.reviewers != rhs.reviewers {return false}
    if lhs._reviewDate != rhs._reviewDate {return false}
    if lhs.notes != rhs.notes {return false}
    if lhs._changes != rhs._changes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_ReviewChanges: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReviewChanges"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{2}membership_requirements_changed\0\u{3}removed_members\0\u{3}review_frequency_changed\0\u{3}review_day_of_month_changed\0\u{3}scoped_removed_members\0\u{b}frequency_changed\0\u{c}\u{1}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularMessageField(value: &self._membershipRequirementsChanged) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.removedMembers) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.reviewFrequencyChanged) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self.reviewDayOfMonthChanged) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.scopedRemovedMembers) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._membershipRequirementsChanged {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.removedMembers.isEmpty {
      try visitor.visitRepeatedStringField(value: self.removedMembers, fieldNumber: 3)
    }
    if self.reviewFrequencyChanged != .unspecified {
      try visitor.visitSingularEnumField(value: self.reviewFrequencyChanged, fieldNumber: 4)
    }
    if self.reviewDayOfMonthChanged != .unspecified {
      try visitor.visitSingularEnumField(value: self.reviewDayOfMonthChanged, fieldNumber: 5)
    }
    if !self.scopedRemovedMembers.isEmpty {
      try visitor.visitRepeatedStringField(value: self.scopedRemovedMembers, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_ReviewChanges, rhs: Teleport_Accesslist_V1_ReviewChanges) -> Bool {
    if lhs._membershipRequirementsChanged != rhs._membershipRequirementsChanged {return false}
    if lhs.removedMembers != rhs.removedMembers {return false}
    if lhs.reviewFrequencyChanged != rhs.reviewFrequencyChanged {return false}
    if lhs.reviewDayOfMonthChanged != rhs.reviewDayOfMonthChanged {return false}
    if lhs.scopedRemovedMembers != rhs.scopedRemovedMembers {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_CurrentUserAssignments: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CurrentUserAssignments"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}ownership_type\0\u{3}membership_type\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.ownershipType) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.membershipType) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.ownershipType != .unspecified {
      try visitor.visitSingularEnumField(value: self.ownershipType, fieldNumber: 1)
    }
    if self.membershipType != .unspecified {
      try visitor.visitSingularEnumField(value: self.membershipType, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_CurrentUserAssignments, rhs: Teleport_Accesslist_V1_CurrentUserAssignments) -> Bool {
    if lhs.ownershipType != rhs.ownershipType {return false}
    if lhs.membershipType != rhs.membershipType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_UserAssignments: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UserAssignments"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}ownership_type\0\u{3}membership_type\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.ownershipType) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.membershipType) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.ownershipType != .unspecified {
      try visitor.visitSingularEnumField(value: self.ownershipType, fieldNumber: 1)
    }
    if self.membershipType != .unspecified {
      try visitor.visitSingularEnumField(value: self.membershipType, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_UserAssignments, rhs: Teleport_Accesslist_V1_UserAssignments) -> Bool {
    if lhs.ownershipType != rhs.ownershipType {return false}
    if lhs.membershipType != rhs.membershipType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Accesslist_V1_AccessListStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AccessListStatus"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}member_count\0\u{3}member_list_count\0\u{3}owner_of\0\u{3}member_of\0\u{3}current_user_assignments\0\u{3}user_assignments\0\u{3}scoped_owner_of\0\u{3}scoped_member_of\0\u{3}owner_displays\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._memberCount) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self._memberListCount) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.ownerOf) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.memberOf) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._currentUserAssignments) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._userAssignments) }()
      case 7: try { try decoder.decodeRepeatedStringField(value: &self.scopedOwnerOf) }()
      case 8: try { try decoder.decodeRepeatedStringField(value: &self.scopedMemberOf) }()
      case 9: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Teleport_Accesslist_V1_UserDisplay>.self, value: &self.ownerDisplays) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._memberCount {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._memberListCount {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
    } }()
    if !self.ownerOf.isEmpty {
      try visitor.visitRepeatedStringField(value: self.ownerOf, fieldNumber: 3)
    }
    if !self.memberOf.isEmpty {
      try visitor.visitRepeatedStringField(value: self.memberOf, fieldNumber: 4)
    }
    try { if let v = self._currentUserAssignments {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._userAssignments {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    if !self.scopedOwnerOf.isEmpty {
      try visitor.visitRepeatedStringField(value: self.scopedOwnerOf, fieldNumber: 7)
    }
    if !self.scopedMemberOf.isEmpty {
      try visitor.visitRepeatedStringField(value: self.scopedMemberOf, fieldNumber: 8)
    }
    if !self.ownerDisplays.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Teleport_Accesslist_V1_UserDisplay>.self, value: self.ownerDisplays, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Accesslist_V1_AccessListStatus, rhs: Teleport_Accesslist_V1_AccessListStatus) -> Bool {
    if lhs._memberCount != rhs._memberCount {return false}
    if lhs._memberListCount != rhs._memberListCount {return false}
    if lhs.ownerOf != rhs.ownerOf {return false}
    if lhs.memberOf != rhs.memberOf {return false}
    if lhs._currentUserAssignments != rhs._currentUserAssignments {return false}
    if lhs._userAssignments != rhs._userAssignments {return false}
    if lhs.scopedOwnerOf != rhs.scopedOwnerOf {return false}
    if lhs.scopedMemberOf != rhs.scopedMemberOf {return false}
    if lhs.ownerDisplays != rhs.ownerDisplays {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
