// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: teleport/lib/teleterm/v1/app.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Teleport
// Copyright (C) 2024 Gravitational, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// App describes an app resource.
public nonisolated struct Teleport_Lib_Teleterm_V1_App: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// uri uniquely identifies an app within Teleport Connect.
  public var uri: String {
    get {_storage._uri}
    set {_uniqueStorage()._uri = newValue}
  }

  /// name is the name of the app.
  public var name: String {
    get {_storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  /// endpoint_uri is the URI to which the app service is going to proxy requests. It corresponds to
  /// app_service.apps[].uri in the Teleport configuration.
  public var endpointUri: String {
    get {_storage._endpointUri}
    set {_uniqueStorage()._endpointUri = newValue}
  }

  /// desc is the app description.
  public var desc: String {
    get {_storage._desc}
    set {_uniqueStorage()._desc = newValue}
  }

  /// aws_console is true if this app is AWS management console.
  public var awsConsole: Bool {
    get {_storage._awsConsole}
    set {_uniqueStorage()._awsConsole = newValue}
  }

  /// public_addr is the public address the application is accessible at.
  ///
  /// If the app resource has its public_addr field set, this field returns the value of public_addr
  /// from the app resource.
  ///
  /// If the app resource does not have public_addr field set, this field returns the name of the app
  /// under the proxy hostname of the cluster to which the app belongs, e.g.,
  /// dumper.root-cluster.com, example-app.leaf-cluster.org.
  ///
  /// In both cases public_addr does not include a port number. This is all cool and fine if the
  /// actual public address and the proxy service share the default port 443. In a scenario where the
  /// proxy uses a non-standard port like 3080 and the public address uses 443, it might cause
  /// problems. public_addr of an app resource cannot include a port number. The backend will reject
  /// such app resource with an error saying "public_addr "example.com:1337" can not contain a port,
  /// applications will be available on the same port as the web proxy". This is not always the case
  /// for custom public addresses. Ultimately, it means that public_addr alone might not be enough to
  /// access the app if either the cluster or the custom address use a port number other than 443.
  ///
  /// public_addr is always empty for SAML applications.
  public var publicAddr: String {
    get {_storage._publicAddr}
    set {_uniqueStorage()._publicAddr = newValue}
  }

  /// friendly_name is a user readable name of the app.
  /// Right now, it is set only for Okta applications.
  /// It is constructed from a label value.
  /// See more in api/types/resource.go.
  public var friendlyName: String {
    get {_storage._friendlyName}
    set {_uniqueStorage()._friendlyName = newValue}
  }

  /// saml_app is true if the application is a SAML Application (Service Provider).
  public var samlApp: Bool {
    get {_storage._samlApp}
    set {_uniqueStorage()._samlApp = newValue}
  }

  /// labels is a list of labels for the app.
  public var labels: [Teleport_Lib_Teleterm_V1_Label] {
    get {_storage._labels}
    set {_uniqueStorage()._labels = newValue}
  }

  /// fqdn is the hostname under which the app is accessible within the root cluster. It is used by
  /// the Web UI to route the requests from the /web/launch URL to the correct app. fqdn by itself
  /// does not include the port number, so fqdn alone cannot be used to launch an app, hence why it's
  /// incorporated into the /web/launch URL.
  ///
  /// If the app belongs to a root cluster, fqdn is equal to public_addr or [name].[root cluster
  /// proxy hostname] if public_addr is not present.
  /// If the app belongs to a leaf cluster, fqdn is equal to [name].[root cluster proxy hostname].
  ///
  /// fqdn is not present for SAML applications. Available only when the app was fetched through the
  /// ListUnifiedResources RPC.
  public var fqdn: String {
    get {_storage._fqdn}
    set {_uniqueStorage()._fqdn = newValue}
  }

  /// aws_roles is a list of AWS IAM roles for the application representing AWS console. Available
  /// only when the app wast fetched through the ListUnifiedResources RPC.
  public var awsRoles: [Teleport_Lib_Teleterm_V1_AWSRole] {
    get {_storage._awsRoles}
    set {_uniqueStorage()._awsRoles = newValue}
  }

  /// TCPPorts is a list of ports and port ranges that an app agent can forward connections to.
  /// Only applicable to TCP App Access.
  /// If this field is not empty, URI is expected to contain no port number and start with the tcp
  /// protocol.
  public var tcpPorts: [Teleport_Lib_Teleterm_V1_PortRange] {
    get {_storage._tcpPorts}
    set {_uniqueStorage()._tcpPorts = newValue}
  }

  /// Subkind of the app resource. Used to differentiate different flavors of app.
  public var subKind: String {
    get {_storage._subKind}
    set {_uniqueStorage()._subKind = newValue}
  }

  /// Defines a permission set that is available on an IdentityCenter account app.
  /// Such apps can be recognized by sub_kind == 'aws_ic_account'.
  public var permissionSets: [Teleport_Lib_Teleterm_V1_IdentityCenterPermissionSet] {
    get {_storage._permissionSets}
    set {_uniqueStorage()._permissionSets = newValue}
  }

  /// supported_feature_ids contains component feature IDs supported by this app and all
  /// other involved components (Auth, Proxy). Used to determine if features like resource
  /// constraints are available.
  public var supportedFeatureIds: [Int32] {
    get {_storage._supportedFeatureIds}
    set {_uniqueStorage()._supportedFeatureIds = newValue}
  }

  /// llm_format is the inference API format of an LLM app, e.g. "anthropic" or
  /// "openai". Empty for non-LLM apps.
  public var llmFormat: String {
    get {_storage._llmFormat}
    set {_uniqueStorage()._llmFormat = newValue}
  }

  /// llm_provider is the inference provider serving an LLM app, e.g.
  /// "anthropic", "openai" or "bedrock". Empty for non-LLM apps.
  public var llmProvider: String {
    get {_storage._llmProvider}
    set {_uniqueStorage()._llmProvider = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// AwsRole describes AWS IAM role.
public nonisolated struct Teleport_Lib_Teleterm_V1_AWSRole: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Name is the full role name with the entire path.
  public var name: String = String()

  /// Display is the role display name.
  public var display: String = String()

  /// ARN is the full role ARN.
  public var arn: String = String()

  /// AccountID is the AWS Account ID this role refers to.
  public var accountID: String = String()

  /// RequiresRequest indicates whether this role requires an access request to be used.
  public var requiresRequest: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// PortRange describes a port range for TCP apps. The range starts with Port and ends with EndPort.
/// PortRange can be used to describe a single port in which case the Port field is the port and the
/// EndPort field is 0.
public nonisolated struct Teleport_Lib_Teleterm_V1_PortRange: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Port describes the start of the range. It must be between 1 and 65535.
  public var port: UInt32 = 0

  /// EndPort describes the end of the range, inclusive. If set, it must be between 2 and 65535 and
  /// be greater than Port when describing a port range. When omitted or set to zero, it signifies
  /// that the port range defines a single port.
  public var endPort: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// RouteToApp is used by the auth service and the app service during cert generation and routing.
/// It's purpose is to point to a specific app within a root cluster. Kind of like an app URI in
/// Connect, but with extra data attached.
public nonisolated struct Teleport_Lib_Teleterm_V1_RouteToApp: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// name is the name of the app within a cluster.
  public var name: String = String()

  /// public_addr is the address under which the app can be reached. It's just the hostname, it does
  /// not include the schema or the port number. See the docs for public_addr of
  /// the App message for a more thorough description.
  public var publicAddr: String = String()

  /// cluster_name is the name of the cluster that the app belongs to. In the case of the root
  /// cluster, it's not guaranteed to be equal to the proxy hostname – the root cluster might have a
  /// distinct name set.
  public var clusterName: String = String()

  /// uri is the URI which the app service is going to proxy requests to.
  public var uri: String = String()

  /// target_port is the port of a multi-port TCP app that the connection is going to be proxied to.
  public var targetPort: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Defines a permission set that is available on an IdentityCenter account app.
public nonisolated struct Teleport_Lib_Teleterm_V1_IdentityCenterPermissionSet: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// AWS-assigned ARN of the permission set.
  public var arn: String = String()

  /// Human-readable name of the permission set.
  public var name: String = String()

  /// ID of the Teleport Account Assignment resource that represents this permission being assigned
  /// on the enclosing Account.
  public var assignmentID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "teleport.lib.teleterm.v1"

nonisolated extension Teleport_Lib_Teleterm_V1_App: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".App"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}uri\0\u{1}name\0\u{3}endpoint_uri\0\u{1}desc\0\u{3}aws_console\0\u{3}public_addr\0\u{3}friendly_name\0\u{3}saml_app\0\u{1}labels\0\u{1}fqdn\0\u{3}aws_roles\0\u{3}tcp_ports\0\u{3}sub_kind\0\u{3}permission_sets\0\u{3}supported_feature_ids\0\u{3}llm_format\0\u{3}llm_provider\0")

  fileprivate class _StorageClass {
    var _uri: String = String()
    var _name: String = String()
    var _endpointUri: String = String()
    var _desc: String = String()
    var _awsConsole: Bool = false
    var _publicAddr: String = String()
    var _friendlyName: String = String()
    var _samlApp: Bool = false
    var _labels: [Teleport_Lib_Teleterm_V1_Label] = []
    var _fqdn: String = String()
    var _awsRoles: [Teleport_Lib_Teleterm_V1_AWSRole] = []
    var _tcpPorts: [Teleport_Lib_Teleterm_V1_PortRange] = []
    var _subKind: String = String()
    var _permissionSets: [Teleport_Lib_Teleterm_V1_IdentityCenterPermissionSet] = []
    var _supportedFeatureIds: [Int32] = []
    var _llmFormat: String = String()
    var _llmProvider: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _uri = source._uri
      _name = source._name
      _endpointUri = source._endpointUri
      _desc = source._desc
      _awsConsole = source._awsConsole
      _publicAddr = source._publicAddr
      _friendlyName = source._friendlyName
      _samlApp = source._samlApp
      _labels = source._labels
      _fqdn = source._fqdn
      _awsRoles = source._awsRoles
      _tcpPorts = source._tcpPorts
      _subKind = source._subKind
      _permissionSets = source._permissionSets
      _supportedFeatureIds = source._supportedFeatureIds
      _llmFormat = source._llmFormat
      _llmProvider = source._llmProvider
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._uri) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._endpointUri) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._desc) }()
        case 5: try { try decoder.decodeSingularBoolField(value: &_storage._awsConsole) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._publicAddr) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._friendlyName) }()
        case 8: try { try decoder.decodeSingularBoolField(value: &_storage._samlApp) }()
        case 9: try { try decoder.decodeRepeatedMessageField(value: &_storage._labels) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._fqdn) }()
        case 11: try { try decoder.decodeRepeatedMessageField(value: &_storage._awsRoles) }()
        case 12: try { try decoder.decodeRepeatedMessageField(value: &_storage._tcpPorts) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._subKind) }()
        case 14: try { try decoder.decodeRepeatedMessageField(value: &_storage._permissionSets) }()
        case 15: try { try decoder.decodeRepeatedInt32Field(value: &_storage._supportedFeatureIds) }()
        case 16: try { try decoder.decodeSingularStringField(value: &_storage._llmFormat) }()
        case 17: try { try decoder.decodeSingularStringField(value: &_storage._llmProvider) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._uri.isEmpty {
        try visitor.visitSingularStringField(value: _storage._uri, fieldNumber: 1)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 2)
      }
      if !_storage._endpointUri.isEmpty {
        try visitor.visitSingularStringField(value: _storage._endpointUri, fieldNumber: 3)
      }
      if !_storage._desc.isEmpty {
        try visitor.visitSingularStringField(value: _storage._desc, fieldNumber: 4)
      }
      if _storage._awsConsole != false {
        try visitor.visitSingularBoolField(value: _storage._awsConsole, fieldNumber: 5)
      }
      if !_storage._publicAddr.isEmpty {
        try visitor.visitSingularStringField(value: _storage._publicAddr, fieldNumber: 6)
      }
      if !_storage._friendlyName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._friendlyName, fieldNumber: 7)
      }
      if _storage._samlApp != false {
        try visitor.visitSingularBoolField(value: _storage._samlApp, fieldNumber: 8)
      }
      if !_storage._labels.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._labels, fieldNumber: 9)
      }
      if !_storage._fqdn.isEmpty {
        try visitor.visitSingularStringField(value: _storage._fqdn, fieldNumber: 10)
      }
      if !_storage._awsRoles.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._awsRoles, fieldNumber: 11)
      }
      if !_storage._tcpPorts.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._tcpPorts, fieldNumber: 12)
      }
      if !_storage._subKind.isEmpty {
        try visitor.visitSingularStringField(value: _storage._subKind, fieldNumber: 13)
      }
      if !_storage._permissionSets.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._permissionSets, fieldNumber: 14)
      }
      if !_storage._supportedFeatureIds.isEmpty {
        try visitor.visitPackedInt32Field(value: _storage._supportedFeatureIds, fieldNumber: 15)
      }
      if !_storage._llmFormat.isEmpty {
        try visitor.visitSingularStringField(value: _storage._llmFormat, fieldNumber: 16)
      }
      if !_storage._llmProvider.isEmpty {
        try visitor.visitSingularStringField(value: _storage._llmProvider, fieldNumber: 17)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_V1_App, rhs: Teleport_Lib_Teleterm_V1_App) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._uri != rhs_storage._uri {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._endpointUri != rhs_storage._endpointUri {return false}
        if _storage._desc != rhs_storage._desc {return false}
        if _storage._awsConsole != rhs_storage._awsConsole {return false}
        if _storage._publicAddr != rhs_storage._publicAddr {return false}
        if _storage._friendlyName != rhs_storage._friendlyName {return false}
        if _storage._samlApp != rhs_storage._samlApp {return false}
        if _storage._labels != rhs_storage._labels {return false}
        if _storage._fqdn != rhs_storage._fqdn {return false}
        if _storage._awsRoles != rhs_storage._awsRoles {return false}
        if _storage._tcpPorts != rhs_storage._tcpPorts {return false}
        if _storage._subKind != rhs_storage._subKind {return false}
        if _storage._permissionSets != rhs_storage._permissionSets {return false}
        if _storage._supportedFeatureIds != rhs_storage._supportedFeatureIds {return false}
        if _storage._llmFormat != rhs_storage._llmFormat {return false}
        if _storage._llmProvider != rhs_storage._llmProvider {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_V1_AWSRole: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AWSRole"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}display\0\u{1}arn\0\u{3}account_id\0\u{3}requires_request\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.display) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.arn) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.accountID) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.requiresRequest) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.display.isEmpty {
      try visitor.visitSingularStringField(value: self.display, fieldNumber: 2)
    }
    if !self.arn.isEmpty {
      try visitor.visitSingularStringField(value: self.arn, fieldNumber: 3)
    }
    if !self.accountID.isEmpty {
      try visitor.visitSingularStringField(value: self.accountID, fieldNumber: 4)
    }
    if self.requiresRequest != false {
      try visitor.visitSingularBoolField(value: self.requiresRequest, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_V1_AWSRole, rhs: Teleport_Lib_Teleterm_V1_AWSRole) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.display != rhs.display {return false}
    if lhs.arn != rhs.arn {return false}
    if lhs.accountID != rhs.accountID {return false}
    if lhs.requiresRequest != rhs.requiresRequest {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_V1_PortRange: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PortRange"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}port\0\u{3}end_port\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.port) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.endPort) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.port != 0 {
      try visitor.visitSingularUInt32Field(value: self.port, fieldNumber: 1)
    }
    if self.endPort != 0 {
      try visitor.visitSingularUInt32Field(value: self.endPort, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_V1_PortRange, rhs: Teleport_Lib_Teleterm_V1_PortRange) -> Bool {
    if lhs.port != rhs.port {return false}
    if lhs.endPort != rhs.endPort {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_V1_RouteToApp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RouteToApp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}public_addr\0\u{3}cluster_name\0\u{1}uri\0\u{3}target_port\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.publicAddr) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.clusterName) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.uri) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.targetPort) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.publicAddr.isEmpty {
      try visitor.visitSingularStringField(value: self.publicAddr, fieldNumber: 2)
    }
    if !self.clusterName.isEmpty {
      try visitor.visitSingularStringField(value: self.clusterName, fieldNumber: 3)
    }
    if !self.uri.isEmpty {
      try visitor.visitSingularStringField(value: self.uri, fieldNumber: 4)
    }
    if self.targetPort != 0 {
      try visitor.visitSingularUInt32Field(value: self.targetPort, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_V1_RouteToApp, rhs: Teleport_Lib_Teleterm_V1_RouteToApp) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.publicAddr != rhs.publicAddr {return false}
    if lhs.clusterName != rhs.clusterName {return false}
    if lhs.uri != rhs.uri {return false}
    if lhs.targetPort != rhs.targetPort {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_V1_IdentityCenterPermissionSet: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IdentityCenterPermissionSet"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}arn\0\u{1}name\0\u{3}assignment_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.arn) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.assignmentID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.arn.isEmpty {
      try visitor.visitSingularStringField(value: self.arn, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.assignmentID.isEmpty {
      try visitor.visitSingularStringField(value: self.assignmentID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_V1_IdentityCenterPermissionSet, rhs: Teleport_Lib_Teleterm_V1_IdentityCenterPermissionSet) -> Bool {
    if lhs.arn != rhs.arn {return false}
    if lhs.name != rhs.name {return false}
    if lhs.assignmentID != rhs.assignmentID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
