// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: teleport/lib/teleterm/v1/database.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Teleport
// Copyright (C) 2023  Gravitational, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Database describes a database (resource kind "db")
public nonisolated struct Teleport_Lib_Teleterm_V1_Database: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// uri is the cluster resource URI
  public var uri: String = String()

  /// name is the name of the database
  public var name: String = String()

  /// desc is the database description
  public var desc: String = String()

  /// protocol is the protocol used by the database
  public var `protocol`: String = String()

  /// type is the database type, self-hosted or cloud-hosted.
  public var type: String = String()

  /// hostname is this database hostname
  public var hostname: String = String()

  /// addr is this database ip address
  public var addr: String = String()

  /// labels is a list of labels for this database
  public var labels: [Teleport_Lib_Teleterm_V1_Label] = []

  /// target_health of the "db_server" that is serving this database.
  public var targetHealth: Teleport_Lib_Teleterm_V1_TargetHealth {
    get {_targetHealth ?? Teleport_Lib_Teleterm_V1_TargetHealth()}
    set {_targetHealth = newValue}
  }
  /// Returns true if `targetHealth` has been explicitly set.
  public var hasTargetHealth: Bool {self._targetHealth != nil}
  /// Clears the value of `targetHealth`. Subsequent reads from it will return its default value.
  public mutating func clearTargetHealth() {self._targetHealth = nil}

  /// gcp_project_id is optional project ID set for GCP Project databases.
  public var gcpProjectID: String = String()

  /// auto_user_provisioning contains database auto-user provisioning information.
  public var autoUserProvisioning: Teleport_Lib_Teleterm_V1_AutoUserProvisioning {
    get {_autoUserProvisioning ?? Teleport_Lib_Teleterm_V1_AutoUserProvisioning()}
    set {_autoUserProvisioning = newValue}
  }
  /// Returns true if `autoUserProvisioning` has been explicitly set.
  public var hasAutoUserProvisioning: Bool {self._autoUserProvisioning != nil}
  /// Clears the value of `autoUserProvisioning`. Subsequent reads from it will return its default value.
  public mutating func clearAutoUserProvisioning() {self._autoUserProvisioning = nil}

  /// database_users is a list of allowed database users that Teleport RBAC permits the user to connect as.
  public var databaseUsers: [String] = []

  /// wildcard_user_allowed is true when the user's role grants access with db_users: ["*"],
  public var wildcardUserAllowed: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _targetHealth: Teleport_Lib_Teleterm_V1_TargetHealth? = nil
  fileprivate var _autoUserProvisioning: Teleport_Lib_Teleterm_V1_AutoUserProvisioning? = nil
}

/// AutoUserProvisioning contains database auto-user provisioning information.
public nonisolated struct Teleport_Lib_Teleterm_V1_AutoUserProvisioning: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// database_roles is a list of database roles that will be assigned to the auto-provisioned database user.
  public var databaseRoles: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// DatabaseServer (db_server) describes a database heartbeat signal
/// reported from an agent (db_service) that is proxying
/// the database.
public nonisolated struct Teleport_Lib_Teleterm_V1_DatabaseServer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var uri: String = String()

  public var hostname: String = String()

  public var hostID: String = String()

  public var targetHealth: Teleport_Lib_Teleterm_V1_TargetHealth {
    get {_targetHealth ?? Teleport_Lib_Teleterm_V1_TargetHealth()}
    set {_targetHealth = newValue}
  }
  /// Returns true if `targetHealth` has been explicitly set.
  public var hasTargetHealth: Bool {self._targetHealth != nil}
  /// Clears the value of `targetHealth`. Subsequent reads from it will return its default value.
  public mutating func clearTargetHealth() {self._targetHealth = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _targetHealth: Teleport_Lib_Teleterm_V1_TargetHealth? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "teleport.lib.teleterm.v1"

nonisolated extension Teleport_Lib_Teleterm_V1_Database: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Database"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}uri\0\u{1}name\0\u{1}desc\0\u{1}protocol\0\u{1}type\0\u{1}hostname\0\u{1}addr\0\u{1}labels\0\u{3}target_health\0\u{3}gcp_project_id\0\u{3}auto_user_provisioning\0\u{3}database_users\0\u{3}wildcard_user_allowed\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.uri) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.desc) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.`protocol`) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.hostname) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.addr) }()
      case 8: try { try decoder.decodeRepeatedMessageField(value: &self.labels) }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._targetHealth) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.gcpProjectID) }()
      case 11: try { try decoder.decodeSingularMessageField(value: &self._autoUserProvisioning) }()
      case 12: try { try decoder.decodeRepeatedStringField(value: &self.databaseUsers) }()
      case 13: try { try decoder.decodeSingularBoolField(value: &self.wildcardUserAllowed) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.uri.isEmpty {
      try visitor.visitSingularStringField(value: self.uri, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.desc.isEmpty {
      try visitor.visitSingularStringField(value: self.desc, fieldNumber: 3)
    }
    if !self.`protocol`.isEmpty {
      try visitor.visitSingularStringField(value: self.`protocol`, fieldNumber: 4)
    }
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 5)
    }
    if !self.hostname.isEmpty {
      try visitor.visitSingularStringField(value: self.hostname, fieldNumber: 6)
    }
    if !self.addr.isEmpty {
      try visitor.visitSingularStringField(value: self.addr, fieldNumber: 7)
    }
    if !self.labels.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.labels, fieldNumber: 8)
    }
    try { if let v = self._targetHealth {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    if !self.gcpProjectID.isEmpty {
      try visitor.visitSingularStringField(value: self.gcpProjectID, fieldNumber: 10)
    }
    try { if let v = self._autoUserProvisioning {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    } }()
    if !self.databaseUsers.isEmpty {
      try visitor.visitRepeatedStringField(value: self.databaseUsers, fieldNumber: 12)
    }
    if self.wildcardUserAllowed != false {
      try visitor.visitSingularBoolField(value: self.wildcardUserAllowed, fieldNumber: 13)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_V1_Database, rhs: Teleport_Lib_Teleterm_V1_Database) -> Bool {
    if lhs.uri != rhs.uri {return false}
    if lhs.name != rhs.name {return false}
    if lhs.desc != rhs.desc {return false}
    if lhs.`protocol` != rhs.`protocol` {return false}
    if lhs.type != rhs.type {return false}
    if lhs.hostname != rhs.hostname {return false}
    if lhs.addr != rhs.addr {return false}
    if lhs.labels != rhs.labels {return false}
    if lhs._targetHealth != rhs._targetHealth {return false}
    if lhs.gcpProjectID != rhs.gcpProjectID {return false}
    if lhs._autoUserProvisioning != rhs._autoUserProvisioning {return false}
    if lhs.databaseUsers != rhs.databaseUsers {return false}
    if lhs.wildcardUserAllowed != rhs.wildcardUserAllowed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_V1_AutoUserProvisioning: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AutoUserProvisioning"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{2}database_roles\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.databaseRoles) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.databaseRoles.isEmpty {
      try visitor.visitRepeatedStringField(value: self.databaseRoles, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_V1_AutoUserProvisioning, rhs: Teleport_Lib_Teleterm_V1_AutoUserProvisioning) -> Bool {
    if lhs.databaseRoles != rhs.databaseRoles {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_V1_DatabaseServer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DatabaseServer"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}uri\0\u{1}hostname\0\u{3}host_id\0\u{3}target_health\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.uri) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.hostname) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.hostID) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._targetHealth) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.uri.isEmpty {
      try visitor.visitSingularStringField(value: self.uri, fieldNumber: 1)
    }
    if !self.hostname.isEmpty {
      try visitor.visitSingularStringField(value: self.hostname, fieldNumber: 2)
    }
    if !self.hostID.isEmpty {
      try visitor.visitSingularStringField(value: self.hostID, fieldNumber: 3)
    }
    try { if let v = self._targetHealth {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_V1_DatabaseServer, rhs: Teleport_Lib_Teleterm_V1_DatabaseServer) -> Bool {
    if lhs.uri != rhs.uri {return false}
    if lhs.hostname != rhs.hostname {return false}
    if lhs.hostID != rhs.hostID {return false}
    if lhs._targetHealth != rhs._targetHealth {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
