// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: teleport/lib/teleterm/v1/kube.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Teleport
// Copyright (C) 2023  Gravitational, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Kube describes connected Kubernetes cluster
public nonisolated struct Teleport_Lib_Teleterm_V1_Kube: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// uri is the kube resource URI
  public var uri: String = String()

  /// name is the kube name
  public var name: String = String()

  /// labels is the kube labels
  public var labels: [Teleport_Lib_Teleterm_V1_Label] = []

  /// target_health is the health of the kube cluster
  public var targetHealth: Teleport_Lib_Teleterm_V1_TargetHealth {
    get {_targetHealth ?? Teleport_Lib_Teleterm_V1_TargetHealth()}
    set {_targetHealth = newValue}
  }
  /// Returns true if `targetHealth` has been explicitly set.
  public var hasTargetHealth: Bool {self._targetHealth != nil}
  /// Clears the value of `targetHealth`. Subsequent reads from it will return its default value.
  public mutating func clearTargetHealth() {self._targetHealth = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _targetHealth: Teleport_Lib_Teleterm_V1_TargetHealth? = nil
}

/// KubeResource describes a kube_cluster's subresource eg: pods, namespaces, etc.
public nonisolated struct Teleport_Lib_Teleterm_V1_KubeResource: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// uri is the kube resource URI
  public var uri: String = String()

  /// kind is the kube subresource kind eg: pods, namespace
  public var kind: String = String()

  /// name is the kube resource name eg: pod name, namespace name
  public var name: String = String()

  /// labels is the kube resource labels
  public var labels: [Teleport_Lib_Teleterm_V1_Label] = []

  /// cluster is the kube cluster name that this kube resource belongs to
  /// eg: the kube cluster that a namespace belongs to
  public var cluster: String = String()

  /// namespace is the kube namespace where the resource is located
  /// note: this field will be blank if this resource "kind" is "namespace",
  /// refer to field "name" for the name of namespace
  public var namespace: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// KubeServer (kube_server) describes a Kube heartbeat signal
/// reported from an agent (kubernetes_service) that is proxying
/// the Kubernetes cluster.
public nonisolated struct Teleport_Lib_Teleterm_V1_KubeServer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var uri: String = String()

  public var hostname: String = String()

  public var hostID: String = String()

  public var targetHealth: Teleport_Lib_Teleterm_V1_TargetHealth {
    get {_targetHealth ?? Teleport_Lib_Teleterm_V1_TargetHealth()}
    set {_targetHealth = newValue}
  }
  /// Returns true if `targetHealth` has been explicitly set.
  public var hasTargetHealth: Bool {self._targetHealth != nil}
  /// Clears the value of `targetHealth`. Subsequent reads from it will return its default value.
  public mutating func clearTargetHealth() {self._targetHealth = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _targetHealth: Teleport_Lib_Teleterm_V1_TargetHealth? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "teleport.lib.teleterm.v1"

nonisolated extension Teleport_Lib_Teleterm_V1_Kube: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Kube"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}uri\0\u{1}name\0\u{1}labels\0\u{3}target_health\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.uri) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.labels) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._targetHealth) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.uri.isEmpty {
      try visitor.visitSingularStringField(value: self.uri, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.labels.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.labels, fieldNumber: 3)
    }
    try { if let v = self._targetHealth {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_V1_Kube, rhs: Teleport_Lib_Teleterm_V1_Kube) -> Bool {
    if lhs.uri != rhs.uri {return false}
    if lhs.name != rhs.name {return false}
    if lhs.labels != rhs.labels {return false}
    if lhs._targetHealth != rhs._targetHealth {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_V1_KubeResource: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".KubeResource"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}uri\0\u{1}kind\0\u{1}name\0\u{1}labels\0\u{1}cluster\0\u{1}namespace\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.uri) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.kind) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.labels) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.cluster) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.namespace) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.uri.isEmpty {
      try visitor.visitSingularStringField(value: self.uri, fieldNumber: 1)
    }
    if !self.kind.isEmpty {
      try visitor.visitSingularStringField(value: self.kind, fieldNumber: 2)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 3)
    }
    if !self.labels.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.labels, fieldNumber: 4)
    }
    if !self.cluster.isEmpty {
      try visitor.visitSingularStringField(value: self.cluster, fieldNumber: 5)
    }
    if !self.namespace.isEmpty {
      try visitor.visitSingularStringField(value: self.namespace, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_V1_KubeResource, rhs: Teleport_Lib_Teleterm_V1_KubeResource) -> Bool {
    if lhs.uri != rhs.uri {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.name != rhs.name {return false}
    if lhs.labels != rhs.labels {return false}
    if lhs.cluster != rhs.cluster {return false}
    if lhs.namespace != rhs.namespace {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_V1_KubeServer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".KubeServer"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}uri\0\u{1}hostname\0\u{3}host_id\0\u{3}target_health\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.uri) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.hostname) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.hostID) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._targetHealth) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.uri.isEmpty {
      try visitor.visitSingularStringField(value: self.uri, fieldNumber: 1)
    }
    if !self.hostname.isEmpty {
      try visitor.visitSingularStringField(value: self.hostname, fieldNumber: 2)
    }
    if !self.hostID.isEmpty {
      try visitor.visitSingularStringField(value: self.hostID, fieldNumber: 3)
    }
    try { if let v = self._targetHealth {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_V1_KubeServer, rhs: Teleport_Lib_Teleterm_V1_KubeServer) -> Bool {
    if lhs.uri != rhs.uri {return false}
    if lhs.hostname != rhs.hostname {return false}
    if lhs.hostID != rhs.hostID {return false}
    if lhs._targetHealth != rhs._targetHealth {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
