// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: teleport/lib/teleterm/auto_update/v1/auto_update_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Teleport
// Copyright (C) 2025 Gravitational, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Source of the config.
public nonisolated enum Teleport_Lib_Teleterm_AutoUpdate_V1_ConfigSource: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// Configuration comes from an environment variable.
  case envVar // = 1

  /// Configuration comes from SOFTWARE\Policies\Teleport\TeleportConnect.
  case policy // = 2

  /// Configuration comes from a hardcoded default.
  case `default` // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .envVar
    case 2: self = .policy
    case 3: self = .default
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .envVar: return 1
    case .policy: return 2
    case .default: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Teleport_Lib_Teleterm_AutoUpdate_V1_ConfigSource] = [
    .unspecified,
    .envVar,
    .policy,
    .default,
  ]

}

/// Request for GetClusterVersions.
public nonisolated struct Teleport_Lib_Teleterm_AutoUpdate_V1_GetClusterVersionsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Response for GetClusterVersions.
public nonisolated struct Teleport_Lib_Teleterm_AutoUpdate_V1_GetClusterVersionsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reachableClusters: [Teleport_Lib_Teleterm_AutoUpdate_V1_ClusterVersionInfo] = []

  public var unreachableClusters: [Teleport_Lib_Teleterm_AutoUpdate_V1_UnreachableCluster] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// ClusterVersionInfo contains tool version information for a reachable cluster.
public nonisolated struct Teleport_Lib_Teleterm_AutoUpdate_V1_ClusterVersionInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// URI of the cluster.
  public var clusterUri: String = String()

  /// Whether the client should automatically update the tools version.
  public var toolsAutoUpdate: Bool = false

  /// Tools version required by this cluster.
  public var toolsVersion: String = String()

  /// Minimum tools version allowed by this cluster.
  public var minToolsVersion: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// UnreachableCluster represents a cluster from which version information could not be retrieved.
public nonisolated struct Teleport_Lib_Teleterm_AutoUpdate_V1_UnreachableCluster: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// URI of the cluster.
  public var clusterUri: String = String()

  /// Error that occurred while retrieving version information.
  public var errorMessage: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Request for GetConfig.
public nonisolated struct Teleport_Lib_Teleterm_AutoUpdate_V1_GetConfigRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Response for GetConfig.
public nonisolated struct Teleport_Lib_Teleterm_AutoUpdate_V1_GetConfigResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A base URL (e.g. cdn.teleport.dev) for downloading packages.
  /// Sources resolved by platform:
  /// * macOS/Linux: The `TELEPORT_CDN_BASE_URL` environment variable.
  /// * Windows: The `CdnBaseUrl` value in the system registry (SOFTWARE\Policies\Teleport\TeleportConnect).
  ///   - HKEY_LOCAL_MACHINE (Machine Policy): Takes precedence over user policies.
  ///   - HKEY_CURRENT_USER (User Policy): Used only for per-user installations if no machine policy is defined.
  ///   - If policy values are missing, falls back to `TELEPORT_CDN_BASE_URL` (deprecated).
  ///
  /// Note: OSS builds require this to be set (via env var or registry), otherwise an empty value is returned.
  public var cdnBaseURL: Teleport_Lib_Teleterm_AutoUpdate_V1_ConfigValue {
    get {_cdnBaseURL ?? Teleport_Lib_Teleterm_AutoUpdate_V1_ConfigValue()}
    set {_cdnBaseURL = newValue}
  }
  /// Returns true if `cdnBaseURL` has been explicitly set.
  public var hasCdnBaseURL: Bool {self._cdnBaseURL != nil}
  /// Clears the value of `cdnBaseURL`. Subsequent reads from it will return its default value.
  public mutating func clearCdnBaseURL() {self._cdnBaseURL = nil}

  /// The specific client tools version to use. The 'off' value disables automatic updates.
  /// Sources resolved by platform:
  /// * macOS/Linux: The `TELEPORT_TOOLS_VERSION` environment variable.
  /// * Windows: The `ToolsVersion` value in the system registry (SOFTWARE\Policies\Teleport\TeleportConnect).
  ///   - HKEY_LOCAL_MACHINE (Machine Policy): Takes precedence over user policies.
  ///   - HKEY_CURRENT_USER (User Policy): Used only for per-user installations if no machine policy is defined.
  ///   - If policy values are missing, falls back to `TELEPORT_TOOLS_VERSION` (deprecated).
  public var toolsVersion: Teleport_Lib_Teleterm_AutoUpdate_V1_ConfigValue {
    get {_toolsVersion ?? Teleport_Lib_Teleterm_AutoUpdate_V1_ConfigValue()}
    set {_toolsVersion = newValue}
  }
  /// Returns true if `toolsVersion` has been explicitly set.
  public var hasToolsVersion: Bool {self._toolsVersion != nil}
  /// Clears the value of `toolsVersion`. Subsequent reads from it will return its default value.
  public mutating func clearToolsVersion() {self._toolsVersion = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _cdnBaseURL: Teleport_Lib_Teleterm_AutoUpdate_V1_ConfigValue? = nil
  fileprivate var _toolsVersion: Teleport_Lib_Teleterm_AutoUpdate_V1_ConfigValue? = nil
}

/// Contains the config value and its source.
public nonisolated struct Teleport_Lib_Teleterm_AutoUpdate_V1_ConfigValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var value: String = String()

  /// Source of the config.
  public var source: Teleport_Lib_Teleterm_AutoUpdate_V1_ConfigSource = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Request for GetInstallationMetadata.
public nonisolated struct Teleport_Lib_Teleterm_AutoUpdate_V1_GetInstallationMetadataRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Response for GetInstallationMetadata.
public nonisolated struct Teleport_Lib_Teleterm_AutoUpdate_V1_GetInstallationMetadataResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Determines whether updates should target a per-machine installation.
  public var isPerMachineInstall: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "teleport.lib.teleterm.auto_update.v1"

nonisolated extension Teleport_Lib_Teleterm_AutoUpdate_V1_ConfigSource: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CONFIG_SOURCE_UNSPECIFIED\0\u{1}CONFIG_SOURCE_ENV_VAR\0\u{1}CONFIG_SOURCE_POLICY\0\u{1}CONFIG_SOURCE_DEFAULT\0")
}

nonisolated extension Teleport_Lib_Teleterm_AutoUpdate_V1_GetClusterVersionsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetClusterVersionsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_AutoUpdate_V1_GetClusterVersionsRequest, rhs: Teleport_Lib_Teleterm_AutoUpdate_V1_GetClusterVersionsRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_AutoUpdate_V1_GetClusterVersionsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetClusterVersionsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}reachable_clusters\0\u{3}unreachable_clusters\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.reachableClusters) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.unreachableClusters) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.reachableClusters.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.reachableClusters, fieldNumber: 1)
    }
    if !self.unreachableClusters.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.unreachableClusters, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_AutoUpdate_V1_GetClusterVersionsResponse, rhs: Teleport_Lib_Teleterm_AutoUpdate_V1_GetClusterVersionsResponse) -> Bool {
    if lhs.reachableClusters != rhs.reachableClusters {return false}
    if lhs.unreachableClusters != rhs.unreachableClusters {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_AutoUpdate_V1_ClusterVersionInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClusterVersionInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}cluster_uri\0\u{3}tools_auto_update\0\u{3}tools_version\0\u{3}min_tools_version\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.clusterUri) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.toolsAutoUpdate) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.toolsVersion) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.minToolsVersion) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.clusterUri.isEmpty {
      try visitor.visitSingularStringField(value: self.clusterUri, fieldNumber: 1)
    }
    if self.toolsAutoUpdate != false {
      try visitor.visitSingularBoolField(value: self.toolsAutoUpdate, fieldNumber: 2)
    }
    if !self.toolsVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.toolsVersion, fieldNumber: 3)
    }
    if !self.minToolsVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.minToolsVersion, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_AutoUpdate_V1_ClusterVersionInfo, rhs: Teleport_Lib_Teleterm_AutoUpdate_V1_ClusterVersionInfo) -> Bool {
    if lhs.clusterUri != rhs.clusterUri {return false}
    if lhs.toolsAutoUpdate != rhs.toolsAutoUpdate {return false}
    if lhs.toolsVersion != rhs.toolsVersion {return false}
    if lhs.minToolsVersion != rhs.minToolsVersion {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_AutoUpdate_V1_UnreachableCluster: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UnreachableCluster"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}cluster_uri\0\u{3}error_message\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.clusterUri) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.errorMessage) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.clusterUri.isEmpty {
      try visitor.visitSingularStringField(value: self.clusterUri, fieldNumber: 1)
    }
    if !self.errorMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.errorMessage, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_AutoUpdate_V1_UnreachableCluster, rhs: Teleport_Lib_Teleterm_AutoUpdate_V1_UnreachableCluster) -> Bool {
    if lhs.clusterUri != rhs.clusterUri {return false}
    if lhs.errorMessage != rhs.errorMessage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_AutoUpdate_V1_GetConfigRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetConfigRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_AutoUpdate_V1_GetConfigRequest, rhs: Teleport_Lib_Teleterm_AutoUpdate_V1_GetConfigRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_AutoUpdate_V1_GetConfigResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetConfigResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}cdn_base_url\0\u{3}tools_version\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._cdnBaseURL) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._toolsVersion) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._cdnBaseURL {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._toolsVersion {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_AutoUpdate_V1_GetConfigResponse, rhs: Teleport_Lib_Teleterm_AutoUpdate_V1_GetConfigResponse) -> Bool {
    if lhs._cdnBaseURL != rhs._cdnBaseURL {return false}
    if lhs._toolsVersion != rhs._toolsVersion {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_AutoUpdate_V1_ConfigValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ConfigValue"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{1}source\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.value) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.source) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 1)
    }
    if self.source != .unspecified {
      try visitor.visitSingularEnumField(value: self.source, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_AutoUpdate_V1_ConfigValue, rhs: Teleport_Lib_Teleterm_AutoUpdate_V1_ConfigValue) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.source != rhs.source {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_AutoUpdate_V1_GetInstallationMetadataRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetInstallationMetadataRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_AutoUpdate_V1_GetInstallationMetadataRequest, rhs: Teleport_Lib_Teleterm_AutoUpdate_V1_GetInstallationMetadataRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Teleport_Lib_Teleterm_AutoUpdate_V1_GetInstallationMetadataResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetInstallationMetadataResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}is_per_machine_install\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.isPerMachineInstall) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.isPerMachineInstall != false {
      try visitor.visitSingularBoolField(value: self.isPerMachineInstall, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Teleport_Lib_Teleterm_AutoUpdate_V1_GetInstallationMetadataResponse, rhs: Teleport_Lib_Teleterm_AutoUpdate_V1_GetInstallationMetadataResponse) -> Bool {
    if lhs.isPerMachineInstall != rhs.isPerMachineInstall {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
