// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: teleport/legacy/types/webauthn/webauthn.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2021 Gravitational, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Credential assertion used for login ceremonies.
public nonisolated struct Webauthn_CredentialAssertion: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var publicKey: Webauthn_PublicKeyCredentialRequestOptions {
    get {_publicKey ?? Webauthn_PublicKeyCredentialRequestOptions()}
    set {_publicKey = newValue}
  }
  /// Returns true if `publicKey` has been explicitly set.
  public var hasPublicKey: Bool {self._publicKey != nil}
  /// Clears the value of `publicKey`. Subsequent reads from it will return its default value.
  public mutating func clearPublicKey() {self._publicKey = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _publicKey: Webauthn_PublicKeyCredentialRequestOptions? = nil
}

/// Request options necessary for credential assertions, aka login ceremonies.
/// See https://www.w3.org/TR/webauthn-2/#dictionary-assertion-options or
/// refer to navigator.credentials.get in your browser.
public nonisolated struct Webauthn_PublicKeyCredentialRequestOptions: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Raw challenge used for assertion.
  public var challenge: Data = Data()

  /// Timeout in milliseconds.
  public var timeoutMs: Int64 = 0

  /// Relying Party ID.
  public var rpID: String = String()

  /// Allowed credentials for assertion.
  public var allowCredentials: [Webauthn_CredentialDescriptor] = []

  /// Extensions supplied by the Relying Party.
  public var extensions: Webauthn_AuthenticationExtensionsClientInputs {
    get {_extensions ?? Webauthn_AuthenticationExtensionsClientInputs()}
    set {_extensions = newValue}
  }
  /// Returns true if `extensions` has been explicitly set.
  public var hasExtensions: Bool {self._extensions != nil}
  /// Clears the value of `extensions`. Subsequent reads from it will return its default value.
  public mutating func clearExtensions() {self._extensions = nil}

  /// User verification requirement.
  public var userVerification: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _extensions: Webauthn_AuthenticationExtensionsClientInputs? = nil
}

/// Assertion response returned by the authenticator.
/// Refer to navigator.credentials.get in your browser.
public nonisolated struct Webauthn_CredentialAssertionResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Type of the credential, usually "public-key".
  public var type: String = String()

  /// Raw Credential ID.
  public var rawID: Data = Data()

  /// Assertion response from the authenticator.
  public var response: Webauthn_AuthenticatorAssertionResponse {
    get {_response ?? Webauthn_AuthenticatorAssertionResponse()}
    set {_response = newValue}
  }
  /// Returns true if `response` has been explicitly set.
  public var hasResponse: Bool {self._response != nil}
  /// Clears the value of `response`. Subsequent reads from it will return its default value.
  public mutating func clearResponse() {self._response = nil}

  /// Extensions supplied by the authenticator.
  public var extensions: Webauthn_AuthenticationExtensionsClientOutputs {
    get {_extensions ?? Webauthn_AuthenticationExtensionsClientOutputs()}
    set {_extensions = newValue}
  }
  /// Returns true if `extensions` has been explicitly set.
  public var hasExtensions: Bool {self._extensions != nil}
  /// Clears the value of `extensions`. Subsequent reads from it will return its default value.
  public mutating func clearExtensions() {self._extensions = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _response: Webauthn_AuthenticatorAssertionResponse? = nil
  fileprivate var _extensions: Webauthn_AuthenticationExtensionsClientOutputs? = nil
}

/// Authenticator assertion response.
/// https://www.w3.org/TR/webauthn-2/#authenticatorassertionresponse
public nonisolated struct Webauthn_AuthenticatorAssertionResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Raw client data JSON, exactly as signed by the authenticator.
  /// https://www.w3.org/TR/webauthn-2/#dictdef-collectedclientdata.
  public var clientDataJson: Data = Data()

  /// Raw authenticator data, exactly as signed by the authenticator.
  /// https://www.w3.org/TR/webauthn-2/#sctn-authenticator-data.
  public var authenticatorData: Data = Data()

  /// Raw assertion signature performed authenticatorData|clientDataJSON.
  /// https://www.w3.org/TR/webauthn-2/#assertion-signature.
  public var signature: Data = Data()

  /// Raw user handle returned by the authenticator, if any.
  public var userHandle: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Credential creation used for registration ceremonies.
public nonisolated struct Webauthn_CredentialCreation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var publicKey: Webauthn_PublicKeyCredentialCreationOptions {
    get {_publicKey ?? Webauthn_PublicKeyCredentialCreationOptions()}
    set {_publicKey = newValue}
  }
  /// Returns true if `publicKey` has been explicitly set.
  public var hasPublicKey: Bool {self._publicKey != nil}
  /// Clears the value of `publicKey`. Subsequent reads from it will return its default value.
  public mutating func clearPublicKey() {self._publicKey = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _publicKey: Webauthn_PublicKeyCredentialCreationOptions? = nil
}

/// Request options necessary for credential creation, aka registration
/// ceremonies.
/// See
/// https://www.w3.org/TR/webauthn-2/#dictdef-publickeycredentialcreationoptions
/// or refer to navigator.credentials.create in your browser.
public nonisolated struct Webauthn_PublicKeyCredentialCreationOptions: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Raw challenge used for creation.
  public var challenge: Data = Data()

  /// Relying party information.
  public var rp: Webauthn_RelyingPartyEntity {
    get {_rp ?? Webauthn_RelyingPartyEntity()}
    set {_rp = newValue}
  }
  /// Returns true if `rp` has been explicitly set.
  public var hasRp: Bool {self._rp != nil}
  /// Clears the value of `rp`. Subsequent reads from it will return its default value.
  public mutating func clearRp() {self._rp = nil}

  /// User information.
  public var user: Webauthn_UserEntity {
    get {_user ?? Webauthn_UserEntity()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  public var hasUser: Bool {self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  public mutating func clearUser() {self._user = nil}

  /// Desired properties for the credential to be created, from most to least
  /// preferred.
  public var credentialParameters: [Webauthn_CredentialParameter] = []

  /// Timeout in milliseconds.
  public var timeoutMs: Int64 = 0

  /// Credentials excluded from the ceremony.
  public var excludeCredentials: [Webauthn_CredentialDescriptor] = []

  /// Attestation requested, defaulting to "none".
  /// https://www.w3.org/TR/webauthn-2/#enumdef-attestationconveyancepreference.
  public var attestation: String = String()

  /// Extensions supplied by the Relying Party.
  public var extensions: Webauthn_AuthenticationExtensionsClientInputs {
    get {_extensions ?? Webauthn_AuthenticationExtensionsClientInputs()}
    set {_extensions = newValue}
  }
  /// Returns true if `extensions` has been explicitly set.
  public var hasExtensions: Bool {self._extensions != nil}
  /// Clears the value of `extensions`. Subsequent reads from it will return its default value.
  public mutating func clearExtensions() {self._extensions = nil}

  /// Authenticator selection criteria for the new credential.
  public var authenticatorSelection: Webauthn_AuthenticatorSelection {
    get {_authenticatorSelection ?? Webauthn_AuthenticatorSelection()}
    set {_authenticatorSelection = newValue}
  }
  /// Returns true if `authenticatorSelection` has been explicitly set.
  public var hasAuthenticatorSelection: Bool {self._authenticatorSelection != nil}
  /// Clears the value of `authenticatorSelection`. Subsequent reads from it will return its default value.
  public mutating func clearAuthenticatorSelection() {self._authenticatorSelection = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _rp: Webauthn_RelyingPartyEntity? = nil
  fileprivate var _user: Webauthn_UserEntity? = nil
  fileprivate var _extensions: Webauthn_AuthenticationExtensionsClientInputs? = nil
  fileprivate var _authenticatorSelection: Webauthn_AuthenticatorSelection? = nil
}

/// Credential creation response returned by the authenticator.
/// Refer to navigator.credentials.create in your browser.
public nonisolated struct Webauthn_CredentialCreationResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Type of the credential, usually "public-key".
  public var type: String = String()

  /// Raw Credential ID.
  public var rawID: Data = Data()

  /// Attestation response from the authenticator.
  public var response: Webauthn_AuthenticatorAttestationResponse {
    get {_response ?? Webauthn_AuthenticatorAttestationResponse()}
    set {_response = newValue}
  }
  /// Returns true if `response` has been explicitly set.
  public var hasResponse: Bool {self._response != nil}
  /// Clears the value of `response`. Subsequent reads from it will return its default value.
  public mutating func clearResponse() {self._response = nil}

  /// Extensions supplied by the authenticator.
  public var extensions: Webauthn_AuthenticationExtensionsClientOutputs {
    get {_extensions ?? Webauthn_AuthenticationExtensionsClientOutputs()}
    set {_extensions = newValue}
  }
  /// Returns true if `extensions` has been explicitly set.
  public var hasExtensions: Bool {self._extensions != nil}
  /// Clears the value of `extensions`. Subsequent reads from it will return its default value.
  public mutating func clearExtensions() {self._extensions = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _response: Webauthn_AuthenticatorAttestationResponse? = nil
  fileprivate var _extensions: Webauthn_AuthenticationExtensionsClientOutputs? = nil
}

/// Attestation response from the authentication, ie, the response to a
/// credential creation request.
/// https://www.w3.org/TR/webauthn-2/#authenticatorattestationresponse.
public nonisolated struct Webauthn_AuthenticatorAttestationResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Raw client data JSON, exactly as signed by the authenticator.
  /// https://www.w3.org/TR/webauthn-2/#dictdef-collectedclientdata.
  public var clientDataJson: Data = Data()

  /// Raw attestation object.
  /// https://www.w3.org/TR/webauthn-2/#attestation-object
  public var attestationObject: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Extensions supplied by the Relying Party during credential assertion or
/// creation.
/// https://www.w3.org/TR/webauthn-2/#client-extension-input
public nonisolated struct Webauthn_AuthenticationExtensionsClientInputs: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// U2F application ID to be used by the authenticator, if any.
  /// Only available if using U2F compatibility mode.
  /// https://www.w3.org/TR/webauthn-2/#sctn-appid-extension.
  public var appID: String = String()

  /// Enables the credProps extension.
  /// https://w3c.github.io/webauthn/#sctn-authenticator-credential-properties-extension
  public var credProps: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Extensions supplied by the authenticator to the Relying Party, during
/// credential assertion or creation.
/// https://www.w3.org/TR/webauthn-2/#client-extension-output.
public nonisolated struct Webauthn_AuthenticationExtensionsClientOutputs: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// If true, the AppID extension was used by the authenticator, which changes
  /// the rpIdHash accordingly.
  /// https://www.w3.org/TR/webauthn-2/#sctn-appid-extension.
  public var appID: Bool = false

  /// Credential properties per credProps extension.
  /// https://w3c.github.io/webauthn/#sctn-authenticator-credential-properties-extension.
  public var credProps: Webauthn_CredentialPropertiesOutput {
    get {_credProps ?? Webauthn_CredentialPropertiesOutput()}
    set {_credProps = newValue}
  }
  /// Returns true if `credProps` has been explicitly set.
  public var hasCredProps: Bool {self._credProps != nil}
  /// Clears the value of `credProps`. Subsequent reads from it will return its default value.
  public mutating func clearCredProps() {self._credProps = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _credProps: Webauthn_CredentialPropertiesOutput? = nil
}

/// CredentialPropertiesOutput is the output of the credProps extension.
public nonisolated struct Webauthn_CredentialPropertiesOutput: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// If true, the created credential is a resident key (regardless of the
  /// AuthenticatorSelection.require_resident_key value).
  /// OPTIONAL by specification.
  public var rk: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Authenticator selection criteria.
/// Restricts the choice of authenticator for credential creation.
public nonisolated struct Webauthn_AuthenticatorSelection: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Authenticator attachment, empty means no particular attachment is
  /// required.
  public var authenticatorAttachment: String = String()

  /// Resident key requirement, if true the authenticator must create a resident
  /// key.
  public var requireResidentKey: Bool = false

  /// User verification requirement for authenticators.
  public var userVerification: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Public key credential descriptor.
/// https://www.w3.org/TR/webauthn-2/#dictdef-publickeycredentialdescriptor.
public nonisolated struct Webauthn_CredentialDescriptor: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Type of the credential, usually "public-key".
  public var type: String = String()

  /// Raw Credential ID.
  public var id: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Parameters for credential creation.
/// https://www.w3.org/TR/webauthn-2/#dictdef-publickeycredentialparameters.
public nonisolated struct Webauthn_CredentialParameter: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Credential type, usually "public-key".
  /// https://www.w3.org/TR/webauthn-2/#enumdef-publickeycredentialtype.
  public var type: String = String()

  /// COSE algorithm specifier.
  /// Most authenticators support exclusively ES256(-7).
  /// https://www.w3.org/TR/webauthn-2/#typedefdef-cosealgorithmidentifier.
  public var alg: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Relying Party information.
/// See https://www.w3.org/TR/webauthn-2/#dictdef-publickeycredentialrpentity and
/// https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/rp.
public nonisolated struct Webauthn_RelyingPartyEntity: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var name: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// User information.
/// See https://www.w3.org/TR/webauthn-2/#dictdef-publickeycredentialuserentity
/// and
/// https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/user.
public nonisolated struct Webauthn_UserEntity: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Raw ID of the user.
  public var id: Data = Data()

  /// Human-palatable name for a user account.
  /// The Relying Party _may_ let the user choose this value.
  public var name: String = String()

  /// Human-palatable name for the user account, intended only for display.
  /// The Relying Party _should_ let the user choose this value.
  public var displayName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "webauthn"

nonisolated extension Webauthn_CredentialAssertion: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CredentialAssertion"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}public_key\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._publicKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._publicKey {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Webauthn_CredentialAssertion, rhs: Webauthn_CredentialAssertion) -> Bool {
    if lhs._publicKey != rhs._publicKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Webauthn_PublicKeyCredentialRequestOptions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PublicKeyCredentialRequestOptions"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}challenge\0\u{3}timeout_ms\0\u{3}rp_id\0\u{3}allow_credentials\0\u{1}extensions\0\u{3}user_verification\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.challenge) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.timeoutMs) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.rpID) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.allowCredentials) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._extensions) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.userVerification) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.challenge.isEmpty {
      try visitor.visitSingularBytesField(value: self.challenge, fieldNumber: 1)
    }
    if self.timeoutMs != 0 {
      try visitor.visitSingularInt64Field(value: self.timeoutMs, fieldNumber: 2)
    }
    if !self.rpID.isEmpty {
      try visitor.visitSingularStringField(value: self.rpID, fieldNumber: 3)
    }
    if !self.allowCredentials.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.allowCredentials, fieldNumber: 4)
    }
    try { if let v = self._extensions {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if !self.userVerification.isEmpty {
      try visitor.visitSingularStringField(value: self.userVerification, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Webauthn_PublicKeyCredentialRequestOptions, rhs: Webauthn_PublicKeyCredentialRequestOptions) -> Bool {
    if lhs.challenge != rhs.challenge {return false}
    if lhs.timeoutMs != rhs.timeoutMs {return false}
    if lhs.rpID != rhs.rpID {return false}
    if lhs.allowCredentials != rhs.allowCredentials {return false}
    if lhs._extensions != rhs._extensions {return false}
    if lhs.userVerification != rhs.userVerification {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Webauthn_CredentialAssertionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CredentialAssertionResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{3}raw_id\0\u{1}response\0\u{1}extensions\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.rawID) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._response) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._extensions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 1)
    }
    if !self.rawID.isEmpty {
      try visitor.visitSingularBytesField(value: self.rawID, fieldNumber: 2)
    }
    try { if let v = self._response {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._extensions {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Webauthn_CredentialAssertionResponse, rhs: Webauthn_CredentialAssertionResponse) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.rawID != rhs.rawID {return false}
    if lhs._response != rhs._response {return false}
    if lhs._extensions != rhs._extensions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Webauthn_AuthenticatorAssertionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AuthenticatorAssertionResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}client_data_json\0\u{3}authenticator_data\0\u{1}signature\0\u{3}user_handle\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.clientDataJson) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.authenticatorData) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.signature) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.userHandle) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.clientDataJson.isEmpty {
      try visitor.visitSingularBytesField(value: self.clientDataJson, fieldNumber: 1)
    }
    if !self.authenticatorData.isEmpty {
      try visitor.visitSingularBytesField(value: self.authenticatorData, fieldNumber: 2)
    }
    if !self.signature.isEmpty {
      try visitor.visitSingularBytesField(value: self.signature, fieldNumber: 3)
    }
    if !self.userHandle.isEmpty {
      try visitor.visitSingularBytesField(value: self.userHandle, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Webauthn_AuthenticatorAssertionResponse, rhs: Webauthn_AuthenticatorAssertionResponse) -> Bool {
    if lhs.clientDataJson != rhs.clientDataJson {return false}
    if lhs.authenticatorData != rhs.authenticatorData {return false}
    if lhs.signature != rhs.signature {return false}
    if lhs.userHandle != rhs.userHandle {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Webauthn_CredentialCreation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CredentialCreation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}public_key\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._publicKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._publicKey {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Webauthn_CredentialCreation, rhs: Webauthn_CredentialCreation) -> Bool {
    if lhs._publicKey != rhs._publicKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Webauthn_PublicKeyCredentialCreationOptions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PublicKeyCredentialCreationOptions"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}challenge\0\u{1}rp\0\u{1}user\0\u{3}credential_parameters\0\u{3}timeout_ms\0\u{3}exclude_credentials\0\u{1}attestation\0\u{1}extensions\0\u{3}authenticator_selection\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.challenge) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._rp) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._user) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.credentialParameters) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.timeoutMs) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.excludeCredentials) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.attestation) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._extensions) }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._authenticatorSelection) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.challenge.isEmpty {
      try visitor.visitSingularBytesField(value: self.challenge, fieldNumber: 1)
    }
    try { if let v = self._rp {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.credentialParameters.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.credentialParameters, fieldNumber: 4)
    }
    if self.timeoutMs != 0 {
      try visitor.visitSingularInt64Field(value: self.timeoutMs, fieldNumber: 5)
    }
    if !self.excludeCredentials.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.excludeCredentials, fieldNumber: 6)
    }
    if !self.attestation.isEmpty {
      try visitor.visitSingularStringField(value: self.attestation, fieldNumber: 7)
    }
    try { if let v = self._extensions {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._authenticatorSelection {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Webauthn_PublicKeyCredentialCreationOptions, rhs: Webauthn_PublicKeyCredentialCreationOptions) -> Bool {
    if lhs.challenge != rhs.challenge {return false}
    if lhs._rp != rhs._rp {return false}
    if lhs._user != rhs._user {return false}
    if lhs.credentialParameters != rhs.credentialParameters {return false}
    if lhs.timeoutMs != rhs.timeoutMs {return false}
    if lhs.excludeCredentials != rhs.excludeCredentials {return false}
    if lhs.attestation != rhs.attestation {return false}
    if lhs._extensions != rhs._extensions {return false}
    if lhs._authenticatorSelection != rhs._authenticatorSelection {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Webauthn_CredentialCreationResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CredentialCreationResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{3}raw_id\0\u{1}response\0\u{1}extensions\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.rawID) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._response) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._extensions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 1)
    }
    if !self.rawID.isEmpty {
      try visitor.visitSingularBytesField(value: self.rawID, fieldNumber: 2)
    }
    try { if let v = self._response {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._extensions {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Webauthn_CredentialCreationResponse, rhs: Webauthn_CredentialCreationResponse) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.rawID != rhs.rawID {return false}
    if lhs._response != rhs._response {return false}
    if lhs._extensions != rhs._extensions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Webauthn_AuthenticatorAttestationResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AuthenticatorAttestationResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}client_data_json\0\u{3}attestation_object\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.clientDataJson) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.attestationObject) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.clientDataJson.isEmpty {
      try visitor.visitSingularBytesField(value: self.clientDataJson, fieldNumber: 1)
    }
    if !self.attestationObject.isEmpty {
      try visitor.visitSingularBytesField(value: self.attestationObject, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Webauthn_AuthenticatorAttestationResponse, rhs: Webauthn_AuthenticatorAttestationResponse) -> Bool {
    if lhs.clientDataJson != rhs.clientDataJson {return false}
    if lhs.attestationObject != rhs.attestationObject {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Webauthn_AuthenticationExtensionsClientInputs: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AuthenticationExtensionsClientInputs"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}app_id\0\u{3}cred_props\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.appID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.credProps) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.appID.isEmpty {
      try visitor.visitSingularStringField(value: self.appID, fieldNumber: 1)
    }
    if self.credProps != false {
      try visitor.visitSingularBoolField(value: self.credProps, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Webauthn_AuthenticationExtensionsClientInputs, rhs: Webauthn_AuthenticationExtensionsClientInputs) -> Bool {
    if lhs.appID != rhs.appID {return false}
    if lhs.credProps != rhs.credProps {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Webauthn_AuthenticationExtensionsClientOutputs: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AuthenticationExtensionsClientOutputs"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}app_id\0\u{3}cred_props\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.appID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._credProps) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.appID != false {
      try visitor.visitSingularBoolField(value: self.appID, fieldNumber: 1)
    }
    try { if let v = self._credProps {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Webauthn_AuthenticationExtensionsClientOutputs, rhs: Webauthn_AuthenticationExtensionsClientOutputs) -> Bool {
    if lhs.appID != rhs.appID {return false}
    if lhs._credProps != rhs._credProps {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Webauthn_CredentialPropertiesOutput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CredentialPropertiesOutput"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}rk\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.rk) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.rk != false {
      try visitor.visitSingularBoolField(value: self.rk, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Webauthn_CredentialPropertiesOutput, rhs: Webauthn_CredentialPropertiesOutput) -> Bool {
    if lhs.rk != rhs.rk {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Webauthn_AuthenticatorSelection: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AuthenticatorSelection"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}authenticator_attachment\0\u{3}require_resident_key\0\u{3}user_verification\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.authenticatorAttachment) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.requireResidentKey) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.userVerification) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.authenticatorAttachment.isEmpty {
      try visitor.visitSingularStringField(value: self.authenticatorAttachment, fieldNumber: 1)
    }
    if self.requireResidentKey != false {
      try visitor.visitSingularBoolField(value: self.requireResidentKey, fieldNumber: 2)
    }
    if !self.userVerification.isEmpty {
      try visitor.visitSingularStringField(value: self.userVerification, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Webauthn_AuthenticatorSelection, rhs: Webauthn_AuthenticatorSelection) -> Bool {
    if lhs.authenticatorAttachment != rhs.authenticatorAttachment {return false}
    if lhs.requireResidentKey != rhs.requireResidentKey {return false}
    if lhs.userVerification != rhs.userVerification {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Webauthn_CredentialDescriptor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CredentialDescriptor"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.id) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 1)
    }
    if !self.id.isEmpty {
      try visitor.visitSingularBytesField(value: self.id, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Webauthn_CredentialDescriptor, rhs: Webauthn_CredentialDescriptor) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Webauthn_CredentialParameter: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CredentialParameter"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}alg\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.alg) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 1)
    }
    if self.alg != 0 {
      try visitor.visitSingularInt32Field(value: self.alg, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Webauthn_CredentialParameter, rhs: Webauthn_CredentialParameter) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.alg != rhs.alg {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Webauthn_RelyingPartyEntity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RelyingPartyEntity"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{b}icon\0\u{c}\u{3}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Webauthn_RelyingPartyEntity, rhs: Webauthn_RelyingPartyEntity) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Webauthn_UserEntity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UserEntity"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{3}display_name\0\u{b}icon\0\u{c}\u{4}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularBytesField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Webauthn_UserEntity, rhs: Webauthn_UserEntity) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
